
let  arr =[
    ["April", "aprel"], 
    ["August", "avgust"], 
    ["CD", "CD"], 
    ["December", "dekabr"], 
    ["February", "Fevral"], 
    ["Friday", "Juma"], 
    ["I", "Men"], 
    ["Internet", "Internet"], 
    ["January", "Yanvar"], 
    ["July", "iyul"], 
    ["June", "iyun"], 
    ["March", "mart"], 
    ["May", "may"], 
    ["Monday", "dushanba"], 
    ["Mr.", "Janob."], 
    ["Mrs.", "Xonim."], 
    ["Ms.", "Xonim."], 
    ["November", "noyabr"], 
    ["OK", "KELISHDIKMI"], 
    ["October", "oktyabr"], 
    ["Saturday", "Shanba"], 
    ["September", "Sentyabr"], 
    ["Sunday", "Yakshanba"], 
    ["TV", "TV"], 
    ["Thursday", "Payshanba"], 
    ["Tuesday", "seshanba"], 
    ["Web site", "Veb-sayt"], 
    ["Wednesday", "chorshanba"], 
    ["a", "a"], 
    ["a.m.", "a.m."], 
    ["abandon", "tashlash"], 
    ["abandoned", "tashlab qo'yilgan"], 
    ["ability", "qobiliyat"], 
    ["able", "qodir"], 
    ["about", "haqida"], 
    ["above", "yuqorida"], 
    ["abroad", "chet elda"], 
    ["absence", "yo'qligi"], 
    ["absent", "yo'q"], 
    ["absolute", "mutlaq"], 
    ["absolutely", "mutlaqo"], 
    ["absorb", "singdirish"], 
    ["abuse", "suiiste'mol"], 
    ["academic", "akademik"], 
    ["accent", "aksent"], 
    ["accept", "qabul qilish"], 
    ["acceptable", "qabul qilinadi"], 
    ["access", "kirish"], 
    ["accident", "baxtsiz hodisa"], 
    ["accidental", "tasodifiy"], 
    ["accompany", "hamrohlik qilish"], 
    ["according to", "ga binoan"], 
    ["account", "hisob"], 
    ["accurate", "aniq"], 
    ["accuse", "ayblash"], 
    ["achieve", "erish"], 
    ["achievement", "muvaffaqiyat"], 
    ["acid", "kislota"], 
    ["acknowledge", "tan olish"], 
    ["acquire", "sotib olish"], 
    ["across", "bo'ylab"], 
    ["act", "harakat"], 
    ["action", "harakat"], 
    ["active", "faol"], 
    ["activist", "faol"], 
    ["activity", "faoliyat"], 
    ["actor", "aktyor"], 
    ["actress", "aktrisa"], 
    ["actual", "haqiqiy"], 
    ["actually", "aslida"], 
    ["ad", "reklama"], 
    ["adapt", "moslashish"], 
    ["add", "qo'shish"], 
    ["add up", "qo'shish"], 
    ["addition", "qo'shimcha"], 
    ["additional", "qo'shimcha"], 
    ["address", "manzil"], 
    ["adequate", "etarli"], 
    ["adjust", "sozlash"], 
    ["administration", "ma'muriyat"], 
    ["admiration", "hayrat"], 
    ["admire", "qoyilman"], 
    ["admit", "tan olish"], 
    ["adopt", "qabul qilish"], 
    ["adult", "kattalar"], 
    ["advance", "avans"], 
    ["advanced", "ilg'or"], 
    ["advantage", "afzallik"], 
    ["adventure", "sarguzasht"], 
    ["advertise", "reklama"], 
    ["advertisement", "reklama"], 
    ["advertising", "reklama"], 
    ["advice", "maslahat"], 
    ["advise", "maslahat"], 
    ["affair", "ish"], 
    ["affect", "ta'sir qilish"], 
    ["affection", "mehr"], 
    ["afford", "qobiliyati"], 
    ["afraid", "qo'rqaman"], 
    ["after", "keyin"], 
    ["afternoon", "peshindan keyin"], 
    ["afterward", "keyin"], 
    ["again", "yana"], 
    ["against", "qarshi"], 
    ["age", "yosh"], 
    ["aged", "qari"], 
    ["agency", "agentlik"], 
    ["agenda", "kun tartibi"], 
    ["agent", "agent"], 
    ["aggressive", "tajovuzkor"], 
    ["ago", "avval"], 
    ["agree", "rozi"], 
    ["agreement", "kelishuv"], 
    ["ahead", "oldinda"], 
    ["aid", "yordam"], 
    ["aim", "maqsad"], 
    ["air", "havo"], 
    ["aircraft", "samolyot"], 
    ["airport", "aeroport"], 
    ["alarm", "signal"], 
    ["alarmed", "tashvish"], 
    ["alarming", "tashvish"], 
    ["alcohol", "alkogol"], 
    ["alcoholic", "alkogolli"], 
    ["alive", "tirik"], 
    ["all", "hamma"], 
    ["allied", "ittifoqdosh"], 
    ["allow of", "ruxsat berish"], 
    ["ally", "ittifoq"], 
    ["almost", "deyarli"], 
    ["alone", "yolg'iz"], 
    ["along", "bo'ylab"], 
    ["alongside", "yonida"], 
    ["aloud", "baland ovozda"], 
    ["alphabet", "alifbo"], 
    ["alphabetical", "alifbo tartibida"], 
    ["already", "allaqachon"], 
    ["also", "shuningdek"], 
    ["alter", "o'zgartirish"], 
    ["alternative", "alternativ"], 
    ["alternatively", "muqobil ravishda"], 
    ["although", "garchi"], 
    ["altogether", "birgalikda"], 
    ["always", "har doim"], 
    ["amaze", "hayratlanish"], 
    ["amazed", "hayratda"], 
    ["amazing", "ajoyib"], 
    ["ambition", "ambitsiya"], 
    ["ambulance", "tez yordam"], 
    ["among", "orada"], 
    ["amount", "miqdori"], 
    ["amuse", "quvnoq"], 
    ["amused", "quvnoq"], 
    ["amusing", "qiziqarli"], 
    ["an", "an"], 
    ["analysis", "tahlil"], 
    ["analyze", "tahlil qilish"], 
    ["ancient", "qadimiy"], 
    ["and", "va"], 
    ["anger", "g'azab"], 
    ["angle", "burchak"], 
    ["angry", "badjahl"], 
    ["animal", "hayvon"], 
    ["ankle", "to'piq"], 
    ["anniversary", "yubiley"], 
    ["announce", "e'lon qilish"], 
    ["announcement", "e'lon"], 
    ["annoy", "bezovta"], 
    ["annoyed", "bezovta"], 
    ["annoying", "zerikarli"], 
    ["annual", "yillik"], 
    ["annually", "har yili"], 
    ["another", "boshqa"], 
    ["answer", "javob"], 
    ["anti-", "qarshi"], 
    ["anticipate", "taxmin qilish"], 
    ["anxiety", "tashvish"], 
    ["anxious", "tashvish"], 
    ["any", "har qanday"], 
    ["anymore", "endi"], 
    ["anyone", "har kim"], 
    ["anything", "har qanday narsa"], 
    ["anyway", "nima bo'lganda ham"], 
    ["anywhere", "har qanday joyda"], 
    ["apart", "alohida"], 
    ["apart from", "dan tashqari"], 
    ["apartment", "kvartira"], 
    ["apologize", "kechirim so'rayman"], 
    ["apparently", "ko'rinishidan"], 
    ["appeal", "Shikoyat qilish"], 
    ["appear", "paydo bo'lish"], 
    ["appearance", "tashqi ko'rinish"], 
    ["apple", "olma"], 
    ["application", "ilova"], 
    ["apply", "qo'llash"], 
    ["appoint", "tayinlash"], 
    ["appointment", "uchrashuv"], 
    ["appreciate", "qadrlayman"], 
    ["approach", "yondashuv"], 
    ["appropriate", "muvofiq"], 
    ["approval", "tasdiqlash"], 
    ["approve", "tasdiqlash"], 
    ["approving", "tasdiqlash"], 
    ["approximate", "taxminan"], 
    ["approximately", "taxminan"], 
    ["area", "maydon"], 
    ["argue", "bahslashish"], 
    ["argument", "dalil"], 
    ["arise", "tur"], 
    ["arm", "qo'l"], 
    ["armed", "qurollangan"], 
    ["arms", "qurol"], 
    ["army", "armiya"], 
    ["around", "atrofida"], 
    ["arrange", "tartibga solish"], 
    ["arrangement", "tartibga solish"], 
    ["arrest", "qo'lga olish"], 
    ["arrival", "kelish"], 
    ["arrive", "kelish"], 
    ["arrow", "o'q"], 
    ["art", "san'at"], 
    ["article", "maqola"], 
    ["artificial", "sun'iy"], 
    ["artist", "rassom"], 
    ["artistic", "badiiy"], 
    ["as", "sifatida"], 
    ["ashamed", "uyaladi"], 
    ["aside", "chetga"], 
    ["aside from", "Bundan tashqari"], 
    ["ask", "so'rang"], 
    ["asleep", "uxlab"], 
    ["aspect", "aspekt"], 
    ["assist", "yordam berish"], 
    ["assistance", "yordam"], 
    ["assistant", "yordamchi"], 
    ["associate", "sherik"], 
    ["association", "assotsiatsiya"], 
    ["assume", "farz qilaylik"], 
    ["assure", "ishonch berish"], 
    ["at", "da"], 
    ["atmosphere", "atmosfera"], 
    ["atom", "atom"], 
    ["attach", "biriktirish"], 
    ["attached", "biriktirilgan"], 
    ["attack", "hujum"], 
    ["attempt", "urinish"], 
    ["attempted", "urinish"], 
    ["attend", "qatnashmoq"], 
    ["attention", "diqqat"], 
    ["attitude", "munosabat"], 
    ["attorney", "advokat"], 
    ["attract", "jalb qilish"], 
    ["attraction", "attraktsion"], 
    ["attractive", "jozibali"], 
    ["audience", "tomoshabinlar"], 
    ["aunt", "xola"], 
    ["author", "muallif"], 
    ["authority", "hokimiyat"], 
    ["automatic", "avtomatik"], 
    ["available", "mavjud"], 
    ["average", "o'rtacha"], 
    ["avoid", "qoching"], 
    ["awake", "uyg'on"], 
    ["award", "mukofot"], 
    ["aware", "xabardor"], 
    ["away", "uzoqda"], 
    ["awful", "dahshatli"], 
    ["awkward", "noqulay"], 
    ["baby", "chaqaloq"], 
    ["back", "orqaga"], 
    ["background", "fon"], 
    ["backward", "orqaga"], 
    ["bacteria", "bakteriyalar"], 
    ["bad", "yomon"], 
    ["badly", "yomon"], 
    ["bag", "sumka"], 
    ["baggage", "Yuk"], 
    ["bake", "pishirish"], 
    ["balance", "muvozanat"], 
    ["ball", "to'p"], 
    ["ban", "taqiq"], 
    ["band", "guruh"], 
    ["bandage", "bandaj"], 
    ["bank", "bank"], 
    ["bar", "bar"], 
    ["barely", "zo'rg'a"], 
    ["bargain", "savdolashish"], 
    ["barrier", "to'siq"], 
    ["base", "tayanch"], 
    ["baseball", "beysbol"], 
    ["basic", "Asosiy"], 
    ["basically", "asosan"], 
    ["basis", "asos"], 
    ["basketball", "basketbol"], 
    ["bath", "Vanna"], 
    ["bathroom", "hammom"], 
    ["battery", "batareya"], 
    ["battle", "jang"], 
    ["bay", "bay"], 
    ["be", "bo'l"], 
    ["beach", "plyaj"], 
    ["beak", "tumshuq"], 
    ["bear", "ayiq"], 
    ["beard", "soqol"], 
    ["beat", "urmoq"], 
    ["beautiful", "chiroyli"], 
    ["beautifully", "chiroyli"], 
    ["beauty", "go'zallik"], 
    ["because", "chunki"], 
    ["become", "bo'lmoq"], 
    ["bed", "to'shak"], 
    ["bedroom", "yotoq xonasi"], 
    ["beef", "mol go'shti"], 
    ["beer", "pivo"], 
    ["before", "oldin"], 
    ["begin", "boshlanishi"], 
    ["beginning", "boshlanishi"], 
    ["behalf", "nomidan"], 
    ["behave", "o'zini tutish"], 
    ["behavior", "xulq-atvor"], 
    ["behind", "orqasida"], 
    ["belief", "e'tiqod"], 
    ["believe", "ishonmoq"], 
    ["bell", "qo'ng'iroq"], 
    ["belong", "mansub"], 
    ["below", "pastda"], 
    ["belt", "kamar"], 
    ["bend", "egilish"], 
    ["beneath", "ostida"], 
    ["benefit", "foyda"], 
    ["bent", "egilgan"], 
    ["beside", "yonida"], 
    ["best", "eng yaxshi"], 
    ["bet", "tikish"], 
    ["better", "yaxshiroq"], 
    ["between", "orasida"], 
    ["beyond", "tashqarida"], 
    ["bicycle", "velosiped"], 
    ["bid 1", "taklif 1"], 
    ["big", "katta"], 
    ["bill", "hisob-kitob"], 
    ["biology", "biologiya"], 
    ["bird", "qush"], 
    ["birth", "tug'ilish"], 
    ["birthday", "tug'ulgan kun"], 
    ["bit", "bit"],
    ["bite", "tishlash"],
    ["bitter", "achchiq"],
    ["bitterly", "achchiq"],
    ["black", "qora"],
    ["blade", "pichoq"],
    ["blame", "ayb"],
    ["blank", "bo'sh"],
    ["blind", "ko'r"],
    ["block", "blok"],
    ["blond", "sariq"],
    ["blood", "qon"],
    ["blow", "puflamoq"],
    ["blue", "ko'k"],
    ["board", "taxta"],
    ["boat", "qayiq"],
    ["body", "tana"],
    ["boil", "qaynatish"],
    ["bomb", "bomba"],
    ["bond", "bog'"],
    ["bone", "suyak"],
    ["book", "kitob"],
    ["boot", "yuklash"],
    ["border", "chegara"],
    ["bore", "zerik"],
    ["bored", "zerikkan"],
    ["boring", "zerikarli"],
    ["born", "tug'ilgan"],
    ["borrow", "qarz olish"],
    ["boss", "boshliq"],
    ["both", "ikkalasi"],
    ["bother", "bezovta"],
    ["bottle", "shisha"],
    ["bottom", "pastki"],
    ["bound", "bog'langan"],
    ["bowl", "kosa"],
    ["box", "quti"],
    ["boy", "bola"],
    ["boyfriend", "yigit"],
    ["brain", "miya"],
    ["branch", "filial"],
    ["brand", "brend"],
    ["brave", "jasur"],
    ["bread", "non"],
    ["break", "tanaffus"],
    ["break in", "eshikni buzib kirish"],
    ["breakfast", "nonushta"],
    ["breast", "ko'krak"],
    ["breath", "nafas"],
    ["breathe", "nafas olish"],
    ["breathing", "nafas olish"],
    ["breed", "zod"],
    ["brick", "g'isht"],
    ["bridge", "ko'prik"],
    ["brief", "qisqa"],
    ["briefly", "qisqacha"],
    ["bright", "yorqin"],
    ["brilliant", "yorqin"],
    ["bring", "olib keling"],
    ["broad", "keng"],
    ["broadcast", "efir"],
    ["broadly", "keng"],
    ["broken", "buzilgan"],
    ["brother", "aka"],
    ["brown", "jigarrang"],
    ["brush", "cho'tka"],
    ["bubble", "qabariq"],
    ["budget", "byudjet"],
    ["build", "qurmoq"],
    ["building", "bino"],
    ["bullet", "o'q"],
    ["bunch", "to'plam"],
    ["burn", "kuyish"],
    ["burn down", "yoqish"],
    ["burst", "portlash"],
    ["bury", "dafn qilmoq"],
    ["bus", "avtobus"],
    ["bush", "buta"],
    ["business", "biznes"],
    ["businessman", "Tadbirkor"],
    ["businesswoman", "Tadbirkor ayol"],
    ["c.", "c."],
    ["cabinet", "kabinet"],
    ["cable", "kabel"],
    ["cake", "tort"],
    ["calculate", "hisoblash"],
    ["calculation", "hisoblash"],
    ["call", "qo'ng'iroq"],
    ["call back", "qayta qo'ng'iroq qilish"],
    ["calm", "sokin"],
    ["calm down", "tinchlaning"],
    ["camera", "kamera"],
    ["camp", "lager"],
    ["campaign", "kampaniya"],
    ["can 1", "1 mumkin"],
    ["can 2", "2 mumkin"],
    ["cancel", "bekor qilish"],
    ["cancer", "saraton"],
    ["candidate", "nomzod"],
    ["candy", "shirinlik"],
    ["cap", "qopqoq"],
    ["capable", "qobiliyatli"],
    ["capacity", "imkoniyat"],
    ["capital", "poytaxt"],
    ["captain", "kapitan"],
    ["capture", "qo'lga olish"],
    ["car", "mashina"],
    ["card", "karta"],
    ["care", "g'amxo'rlik"],
    ["career", "karera"],
    ["careful", "ehtiyot"],
    ["careless", "beparvo"],
    ["carpet", "gilam"],
    ["carrot", "sabzi"],
    ["carry", "olib yurish"],
    ["carry on", "davom etish"],
    ["case", "holat"],
    ["cash", "naqd pul"],
    ["cast", "to'qimalar"],
    ["cat", "mushuk"],
    ["catch", "ushlash"],
    ["category", "toifa"],
    ["cattle", "qoramol"],
    ["cause", "sabab"],
    ["cease", "to'xtatish"],
    ["ceiling", "ship"],
    ["celebrate", "bayramlash"],
    ["celebration", "bayram"],
    ["cell", "hujayra"],
    ["cell phone", "Mobil telefon"],
    ["cent", "tsent"],
    ["center", "markaz"],
    ["centimeter", "santimetr"],
    ["central", "markaziy"],
    ["century", "asr"],
    ["ceremony", "marosim"],
    ["certain", "aniq"],
    ["certainly", "albatta"],
    ["certificate", "sertifikat"],
    ["chain", "zanjir"],
    ["chair", "stul"],
    ["chairman", "rais"],
    ["chairwoman", "rais ayol"],
    ["challenge", "qidiruv"],
    ["chamber", "kamera"],
    ["chance", "imkoniyat"],
    ["change", "o'zgartirish"],
    ["channel", "kanal"],
    ["chapter", "bob"],
    ["character", "belgi"],
    ["characteristic", "xarakterli"],
    ["charge", "zaryad"],
    ["charity", "xayriya"],
    ["chart", "diagramma"],
    ["chase", "ketidan quvmoq"],
    ["chat", "chat"],
    ["cheap", "arzon"],
    ["cheaply", "arzon"],
    ["cheat", "aldash"],
    ["check", "tekshirish"],
    ["cheerful", "quvnoq"],
    ["cheese", "pishloq"],
    ["chemical", "kimyoviy"],
    ["chemist", "kimyogar"],
    ["chemistry", "kimyo"],
    ["chest", "ko'krak"],
    ["chew", "chaynash"],
    ["chicken", "tovuq"],
    ["chief", "boshliq"],
    ["child", "bola"],
    ["childhood", "bolalik"],
    ["chin", "iyak"],
    ["chip", "chip"],
    ["chocolate", "shokolad"],
    ["choice", "tanlov"],
    ["choose", "tanlash"],
    ["chop", "chop"],
    ["church", "cherkov"],
    ["cigarette", "sigaret"],
    ["circle", "doira"],
    ["circumstance", "vaziyat"],
    ["citizen", "fuqaro"],
    ["city", "shahar"],
    ["civil", "fuqarolik"],
    ["claim", "Talab"],
    ["class", "sinf"],
    ["classic", "klassik"],
    ["classroom", "sinf xonasi"],
    ["clean", "toza"],
    ["clear", "aniq"],
    ["clear out", "tozalash"],
    ["clearly", "aniq"],
    ["clerk", "kotib"],
    ["click", "bosing"],
    ["client", "mijoz"],
    ["climate", "iqlim"],
    ["climb", "ko'tarilish"],
    ["clock", "soat"],
    ["close 1", "1-yopiq"],
    ["close 2", "2 yaqin"],
    ["closed", "yopiq"],
    ["closet", "shkaf"],
    ["cloth", "mato"],
    ["clothes", "kiyim"],
    ["clothing", "kiyim"],
    ["cloud", "bulut"],
    ["club", "klub"],
    ["cm", "sm"],
    ["coach", "murabbiy"],
    ["coal", "ko'mir"],
    ["coast", "qirg'oq"],
    ["coat", "palto"],
    ["code", "kod"],
    ["coffee", "kofe"],
    ["coin", "tanga"],
    ["cold", "sovuq"],
    ["coldly", "sovuq"],
    ["collapse", "qulash"],
    ["colleague", "hamkasb"],
    ["collect", "yig'ish"],
    ["collection", "to'plam"],
    ["college", "kollej"],
    ["color", "rang"],
    ["column", "ustun"],
    ["combination", "kombinatsiya"],
    ["combine", "aralashtirmoq"],
    ["come", "kel"],
    ["come about", "kelish"],
    ["come away", "ketmoq"],
    ["come on", "qo'ysangchi; qani endi"],
    ["come over", "bu yerga kel"],
    ["comedy", "komediya"],
    ["comfort", "konfor"],
    ["comfortable", "qulay"],
    ["comfortably", "qulay"],
    ["command", "buyruq"],
    ["comment", "sharh"],
    ["commercial", "tijorat"],
    ["commission", "komissiya"],
    ["commit", "majburiyat"],
    ["commitment", "majburiyat"],
    ["committee", "qo'mita"],
    ["common", "umumiy"],
    ["commonly", "odatda"],
    ["communicate", "muloqot"],
    ["communication", "aloqa"],
    ["community", "jamoa"],
    ["company", "kompaniya"],
    ["compare", "taqqoslash"],
    ["comparison", "taqqoslash"],
    ["compete", "raqobat"],
    ["competition", "musobaqa"],
    ["competitive", "raqobatbardosh"],
    ["complain", "shikoyat qilish"],
    ["complete", "to'liq"],
    ["completely", "butunlay"],
    ["complex", "kompleks"],
    ["complicate", "murakkab"],
    ["complicated", "murakkab"],
    ["component", "komponent"],
    ["computer", "kompyuter"],
    ["concentrate", "kontsentratsiya"],
    ["concentration", "diqqat"],
    ["concept", "kontseptsiya"],
    ["concern", "tashvish"],
    ["concerned", "xavotir"],
    ["concerning", "to'g'risida"],
    ["concert", "konsert"],
    ["conclude", "xulosa qilish"],
    ["conclusion", "xulosa"],
    ["concrete", "beton"],
    ["condition", "shart"],
    ["conduct", "o'tkazish"],
    ["conference", "konferensiya"],
    ["confidence", "ishonch"],
    ["confident", "o'ziga ishongan"],
    ["confirm", "tasdiqlash"],
    ["conflict", "mojaro"],
    ["confront", "yuqtirish"],
    ["confuse", "chalkash"],
    ["confused", "chalkash"],
    ["confusing", "chalkash"],
    ["confusion", "chalkashlik"],
    ["congratulation", "tabriklash"],
    ["congress", "Kongress"],
    ["connect", "ulanmoq"],
    ["connection", "ulanish"],
    ["conscious", "ongli"],
    ["consequence", "oqibat"],
    ["conservative", "konservativ"],
    ["consider", "o'ylab ko'ring"],
    ["considerable", "sezilarli"],
    ["considerably", "juda"],
    ["consideration", "mulohaza"],
    ["consist", "o'z ichiga oladi"],
    ["consistent", "mos keluvchi"],
    ["constant", "doimiy"],
    ["constantly", "doimiy"],
    ["construct", "qurilish"],
    ["construction", "qurilish"],
    ["consult", "maslahat"],
    ["consumer", "iste'molchi"],
    ["contact", "aloqa"],
    ["contain", "o'z ichiga oladi"],
    ["container", "idish"],
    ["contemporary", "zamonaviy"],
    ["content 1", "tarkib 1"],
    ["contest", "tanlov"],
    ["context", "kontekst"],
    ["continent", "materik"],
    ["continue", "davom etish"],
    ["continuous", "davomiy"],
    ["contract", "shartnoma"],
    ["contrast", "kontrast"],
    ["contrasting", "kontrast"],
    ["contribute", "hissa qo'shish"],
    ["contribution", "hissa"],
    ["control", "boshqaruv"],
    ["controlled", "nazorat ostida"],
    ["convenient", "qulay"],
    ["convention", "Konventsiya"],
    ["conventional", "an'anaviy"],
    ["conversation", "suhbat"],
    ["convert", "aylantirish"],
    ["convince", "ishontirish"],
    ["cook", "oshpaz"],
    ["cookie", "cookie"],
    ["cooking", "pishirish"],
    ["cool", "salqin"],
    ["cooperation", "hamkorlik"],
    ["cope", "engish"],
    ["copy", "nusxa"],
    ["core", "yadro"],
    ["corner", "burchak"],
    ["correct", "to'g'ri"],
    ["cost", "xarajat"],
    ["cottage", "dacha"],
    ["cotton", "paxta"],
    ["cough", "yo'tal"],
    ["could", "mumkin"],
    ["council", "kengash"],
    ["count", "hisoblash"],
    ["counter", "taymer"],
    ["country", "mamlakat"],
    ["countryside", "Qishloq joy"],
    ["county", "tuman"],
    ["couple", "er-xotin"],
    ["courage", "jasorat"],
    ["course", "kurs"],
    ["court", "sud"],
    ["cousin", "amakivachcha"],
    ["cover", "qopqoq"],
    ["covered", "qoplangan"],
    ["covering", "qoplash"],
    ["cow", "sigir"],
    ["crack", "yorilish"],
    ["cracked", "yorilgan"],
    ["craft", "hunarmandchilik"],
    ["crash", "halokat"],
    ["crazy", "jinni"],
    ["cream", "krem"],
    ["create", "yaratmoq"],
    ["creation", "yaratilish"],
    ["creative", "ijodiy"],
    ["creature", "maxluq"],
    ["credit", "kredit"],
    ["credit card", "kredit kartasi"],
    ["crime", "jinoyat"],
    ["criminal", "jinoyatchi"],
    ["crisis", "inqiroz"],
    ["crisp", "tiniq"],
    ["criterion", "mezon"],
    ["critic", "tanqidchi"],
    ["critical", "tanqidiy"],
    ["criticism", "tanqid"],
    ["criticize", "tanqid qilish"],
    ["crop", "ekin"],
    ["cross", "kesib o'tish"],
    ["crowd", "olomon"],
    ["crowded", "olomon"],
    ["crown", "toj"],
    ["crucial", "muhim"],
    ["cruel", "shafqatsiz"],
    ["crush", "ezish"],
    ["cry", "yig'lash"],
    ["ct.", "ct."],
    ["cultural", "madaniy"],
    ["culture", "madaniyat"],
    ["cup", "chashka"],
    ["cupboard", "Javon"],
    ["cure", "davo"],
    ["curious", "qiziq"],
    ["curl", "jingalak"],
    ["curl up", "buklanish"],
    ["curly", "jingalak"],
    ["current", "joriy"],
    ["currently", "hozirda"],
    ["curtain", "parda"],
    ["curve", "egri"],
    ["curved", "qiyshiq"],
    ["custom", "maxsus"],
    ["customer", "mijoz"],
    ["customs", "Bojxona"],
    ["cut", "kesish"],
    ["cut down", "kesmoq"],
    ["cute", "yoqimli"],
    ["cycle", "tsikl"],
    ["cycling", "velosiped"],
    ["dad", "dada"],
    ["daily", "kundalik"],
    ["damage", "zarar"],
    ["damp", "nam"],
    ["dance", "raqs"],
    ["dancer", "raqqosa"],
    ["dancing", "raqsga tushish"],
    ["danger", "Xavfli"],
    ["dangerous", "xavfli"],
    ["dare", "jasorat"],
    ["dark", "qorong'i"],
    ["data", "ma'lumotlar"],
    ["date", "sana"],
    ["date back", "Orqaga sana"],
    ["daughter", "qizim"],
    ["day", "kun"],
    ["dead", "o'lik"],
    ["deaf", "kar"],
    ["deal", "shartnoma"],
    ["dear", "azizim"],
    ["death", "o'lim"],
    ["debate", "munozara"],
    ["debt", "qarz"],
    ["decade", "o'n yil"],
    ["decay", "parchalanish"],
    ["decent", "munosib"],
    ["decide", "qaror"],
    ["decision", "qaror"],
    ["declare", "e'lon qilish"],
    ["decline", "kamayish"],
    ["decorate", "bezatish"],
    ["decoration", "bezatish"],
    ["decorative", "dekorativ"],
    ["decrease", "kamayish"],
    ["deep", "chuqur"],
    ["deeply", "chuqur"],
    ["defeat", "mag'lubiyat"],
    ["defend", "himoya qilish"],
    ["defense", "mudofaa"],
    ["define", "aniqlash"],
    ["definite", "aniq"],
    ["definitely", "albatta"],
    ["definition", "ta'rif"],
    ["degree", "daraja"],
    ["delay", "kechikish"],
    ["deliberate", "qasddan"],
    ["deliberately", "qasddan"],
    ["delicate", "nozik"],
    ["delight", "zavq"],
    ["deliver", "etkazib berish"],
    ["delivery", "etkazib berish"],
    ["demand", "talab"],
    ["democracy", "demokratiya"],
    ["democratic", "demokratik"],
    ["demonstrate", "namoyish qilish"],
    ["demonstration", "namoyish"],
    ["dentist", "tish shifokori"],
    ["deny", "inkor"],
    ["department", "Bo'lim"],
    ["departure", "ketish"],
    ["depend", "bog'liq"],
    ["depend on", "bog'liq"],
    ["deposit", "depozit"],
    ["depress", "depressiya"],
    ["depressed", "depressiya"],
    ["depressing", "depressiv"],
    ["depth", "chuqurlik"],
    ["derive", "olish"],
    ["derive from", "dan olingan"],
    ["describe", "ta'riflash"],
    ["description", "tavsif"],
    ["e-mail", "elektron pochta"],
    ["e.g.", "masalan"],
    ["each", "har biri"],
    ["each other", "bir-biriga, bir-birini, o'zaro"],
    ["eager", "ishtirokchi"],
    ["ear", "quloq"],
    ["early", "erta"],
    ["earn", "ishlab topmoq"],
    ["earth", "yer"],
    ["ease", "osonlik"],
    ["easily", "osonlik bilan"],
    ["east", "sharq"],
    ["eastern", "sharqiy"],
    ["easy", "oson"],
    ["eat", "yemoq"],
    ["eat up", "ovqat yeyish"],
    ["economic", "iqtisodiy"],
    ["economics", "iqtisod"],
    ["economy", "iqtisod"],
    ["edge", "chekka"],
    ["edition", "nashr"],
    ["editor", "muharrir"],
    ["educate", "tarbiya berish"],
    ["educated", "ma'lumotli"],
    ["education", "ta'lim"],
    ["educational", "ta'lim"],
    ["effect", "ta'sir"],
    ["effective", "samarali"],
    ["effectively", "samarali"],
    ["efficient", "samarali"],
    ["effort", "harakat"],
    ["egg", "tuxum"],
    ["either", "yoki"],
    ["elbow", "tirsak"],
    ["elderly", "keksalar"],
    ["elect", "tanlangan"],
    ["election", "saylov"],
    ["electric", "elektr"],
    ["electrical", "elektr"],
    ["electricity", "elektr"],
    ["electronic", "elektron"],
    ["elegant", "oqlangan"],
    ["element", "element"],
    ["elevator", "lift"],
    ["eliminate", "yo'q qilish"],
    ["else", "boshqa"],
    ["elsewhere", "boshqa joyda"],
    ["embarrass", "xijolat"],
    ["embarrassed", "xijolat"],
    ["embarrassing", "xijolatli"],
    ["embarrassment", "xijolat"],
    ["emerge", "paydo bo'lish"],
    ["emergency", "favqulodda vaziyat"],
    ["emotion", "hissiyot"],
    ["emotional", "hissiy"],
    ["emphasis", "ta'kid"],
    ["emphasize", "ta'kidlash"],
    ["empire", "imperiya"],
    ["employ", "ishlash"],
    ["employee", "xodim"],
    ["employer", "ish beruvchi"],
    ["employment", "ish bilan ta'minlash"],
    ["empty", "bo'sh"],
    ["enable", "yoqish"],
    ["encounter", "uchrashuv"],
    ["encourage", "rag'batlantirish"],
    ["encouragement", "rag'batlantirish"],
    ["end", "oxiri"],
    ["ending", "tugatish"],
    ["enemy", "dushman"],
    ["energy", "energiya"],
    ["engage", "jalb qilish"],
    ["engaged", "unashtirilgan"],
    ["engine", "dvigatel"],
    ["engineer", "muhandis"],
    ["engineering", "muhandislik"],
    ["enjoy", "bahramand bo'ling"],
    ["enjoyable", "quvonchli"],
    ["enjoyment", "zavq"],
    ["enormous", "katta"],
    ["enough", "yetarli"],
    ["ensure", "ta'minlash"],
    ["enter", "kirish"],
    ["entertain", "ko'ngil ochish"],
    ["entertainer", "ko'ngilochar"],
    ["entertaining", "ko'ngilochar"],
    ["entertainment", "o'yin-kulgi"],
    ["enthusiasm", "ishtiyoq"],
    ["enthusiastic", "ishtiyoqli"],
    ["entire", "butun"],
    ["entirely", "butunlay"],
    ["entitle", "huquq"],
    ["entrance 1", "1-kirish"],
    ["entry", "kirish"],
    ["envelope", "konvert"],
    ["environment", "atrof-muhit"],
    ["environmental", "ekologik"],
    ["equal", "teng"],
    ["equally", "teng"],
    ["equipment", "uskunalar"],
    ["equivalent", "ekvivalent"],
    ["era", "asr"],
    ["error", "xato"],
    ["escape", "qochish"],
    ["especially", "ayniqsa"],
    ["essay", "insho"],
    ["essential", "asosiy"],
    ["essentially", "aslida"],
    ["establish", "o'rnatish"],
    ["estate", "mulk"],
    ["estimate", "baholash"],
    ["etc.", "va boshqalar."],
    ["ethnic", "etnik"],
    ["even", "juft"],
    ["evening", "oqshom"],
    ["event", "voqea"],
    ["eventually", "oxir-oqibat"],
    ["ever", "hamisha"],
    ["every", "har bir"],
    ["everyone", "hamma"],
    ["everything", "hamma narsa"],
    ["everywhere", "hamma joyda"],
    ["evidence", "dalil"],
    ["evil", "yomon"],
    ["ex-", "sobiq"],
    ["exact", "aniq"],
    ["exactly", "aniq"],
    ["exaggerate", "bo'rttirib yuborish"],
    ["exaggerated", "bo'rttirilgan"],
    ["exam", "imtihon"],
    ["examination", "imtihon"],
    ["examine", "Imtihon"],
    ["example", "misol"],
    ["excellent", "a'lo"],
    ["except", "bundan tashqari"],
    ["exception", "istisno"],
    ["exchange", "almashtirish"],
    ["excite", "hayajonlantirish"],
    ["excited", "hayajonlangan"],
    ["excitement", "hayajon"],
    ["exciting", "hayajonli"],
    ["exclude", "istisno"],
    ["excluding", "istisno"],
    ["excuse", "uzr"],
    ["executive", "ijro etuvchi"],
    ["exercise", "mashq"],
    ["exhibit", "ko'rgazma"],
    ["exhibition", "ko'rgazma"],
    ["exist", "mavjud"],
    ["existence", "mavjudlik"],
    ["exit", "Chiqish"],
    ["expand", "kengaytirish"],
    ["expect", "kutish"],
    ["expectation", "kutish"],
    ["expected", "kutilgan"],
    ["expense", "xarajat"],
    ["expensive", "qimmat"],
    ["experience", "tajriba"],
    ["experienced", "tajribali"],
    ["experiment", "tajriba"],
    ["expert", "mutaxassis"],
    ["explain", "tushuntirish"],
    ["explanation", "tushuntirish"],
    ["explode", "portlash"],
    ["explore", "tadqiq qilish"],
    ["explosion", "portlash"],
    ["export", "eksport"],
    ["expose", "fosh qilish"],
    ["express", "ekspress"],
    ["expression", "ifoda"],
    ["extend", "uzaytirish"],
    ["extension", "kengaytma"],
    ["extensive", "keng"],
    ["extent", "miqyosi"],
    ["extra", "qo'shimcha"],
    ["extraordinary", "g'ayrioddiy"],
    ["extreme", "ekstremal"],
    ["extremely", "juda"],
    ["eye", "ko'z"],
    ["face", "yuz"],
    ["facility", "qulaylik"],
    ["fact", "haqiqat"],
    ["factor", "omil"],
    ["factory", "zavod"],
    ["fail", "muvaffaqiyatsiz"],
    ["failure", "muvaffaqiyatsizlik"],
    ["faint", "holsiz"],
    ["fair", "adolatli"],
    ["fairly", "odilona"],,
    ["faith",      "imon"],
    ["faithful",      "sodiq"],
    ["faithfully",      "sadoqat bilan"],
    ["fall",      "kuz"],
    ["false",      "yolg'on"],
    ["fame",      "shon-sharaf"],
    ["familiar",      "tanish"],
    ["family",      "oila"],
    ["famous",      "mashhur"],
    ["fan",      "muxlis"],
    ["fancy",      "xushbichim"],
    ["far",      "uzoq"],
    ["farm",      "ferma"],
    ["farmer",      "fermer"],
    ["farming",      "dehqonchilik"],
    ["farther",      "uzoqroq"],
    ["farthest",      "eng uzoq"],
    ["fashion",      "moda"],
    ["fashionable",      "moda"],
    ["fast",      "tez"],
    ["fasten",      "bog'lash"],
    ["fat",      "yog '"],
    ["father",      "ota"],
    ["fault",      "ayb"],
    ["favor",      "marhamat"],
    ["favorite",      "sevimli"],
    ["fear",      "qo'rquv"],
    ["feather",      "tuklar"],
    ["feature",      "xususiyat"],
    ["federal",      "federal"],
    ["fee",      "haq"],
    ["feed",      "oziq"],
    ["feel",      "his"],
    ["feeling",      "hissiyot"],
    ["fellow",      "do'stim"],
    ["female",      "ayol"],
    ["fence",      "panjara"],
    ["festival",      "festival"],
    ["fever",      "isitma"],
    ["few",      "bir necha"],
    ["field",      "maydon"],
    ["fight",      "jang"],
    ["figure",      "raqam"],
    ["file",      "fayl"],
    ["fill",      "to'ldirish"],
    ["fill up",      "to'ldirish"],
    ["film",      "film"],
    ["final",      "yakuniy"],
    ["finally",      "nihoyat"],
    ["finance",      "Moliya"],
    ["financial",      "moliyaviy"],
    ["find",      "topish"],
    ["find out",      "aniqlash"],
    ["fine",      "yaxshi"],
    ["finely",      "yaxshi"],
    ["finger",      "barmoq"],
    ["finish",      "tugatish"],
    ["finished",      "tugallangan"],
    ["fire",      "olov"],
    ["firm",      "qattiq"],
    ["firmly",      "qat'iy"],
    ["first",      "birinchi"],
    ["fish",      "baliq"],
    ["fishing",      "baliq ovlash"],
    ["fit",      "mos"],
    ["fix",      "tuzatish"],
    ["fixed",      "qat'iy"],
    ["flag",      "bayroq"],
    ["flame",      "olov"],
    ["flash",      "chaqmoq"],
    ["flat",      "tekis"],
    ["flavor",      "lazzat"],
    ["flesh",      "tana"],
    ["flight",      "parvoz"],
    ["float",      "suzuvchi"],
    ["flood",      "toshqin"],
    ["floor",      "qavat"],
    ["flour",      "un"],
    ["flow",      "oqim"],
    ["flower",      "gul"],
    ["flu",      "gripp"],
    ["fly",      "pashsha"],
    ["flying",      "uchish"],
    ["focus",      "fokus"],
    ["fold",      "katlama"],
    ["folding",      "katlama"],
    ["folk",      "xalq"],
    ["follow",      "kuzatish"],
    ["following",      "kuzatish"],
    ["food",      "ovqat"],
    ["foot",      "oyoq"],
    ["football",      "futbol"],
    ["for",      "uchun"],
    ["force",      "kuch"],
    ["forecast",      "prognoz"],
    ["foreign",      "xorijiy"],
    ["forest",      "o'rmon"],
    ["forever",      "abadiy"],
    ["forget",      "unutish"],
    ["forgive",      "kechir"],
    ["fork",      "vilka"],
    ["form",      "shakl"],
    ["formal",      "rasmiy"],
    ["former",      "sobiq"],
    ["formerly",      "avval"],
    ["formula",      "formula"],
    ["fortune",      "omad"],
    ["forward",      "oldinga"],
    ["found",      "topildi"],
    ["foundation",      "poydevor"],
    ["frame",      "ramka"],
    ["free",      "ozod"],
    ["freedom",      "erkinlik"],
    ["freely",      "erkin"],
    ["freeze",      "muzlatish"],
    ["frequent",      "tez-tez"],
    ["frequently",      "tez-tez"],
    ["fresh",      "yangi"],
    ["freshly",      "yangi"],
    ["friend",      "do'st"],
    ["friendly",      "do'stona"],
    ["friendship",      "do'stlik"],
    ["frighten",      "qo'rqitmoq"],
    ["frightened",      "qo'rqib ketdi"],
    ["frightening",      "qo'rqinchli"],
    ["from",      "dan"],
    ["front",      "old"],
    ["frozen",      "muzlatilgan"],
    ["fruit",      "meva"],
    ["fry",      "qovurish"],
    ["fuel",      "yoqilg'i"],
    ["full",      "to'liq"],
    ["fully",      "to'liq"],
    ["fun",      "qiziqarli"],
    ["function",      "funktsiya"],
    ["fund",      "fond"],
    ["fundamental",      "asosiy"],
    ["funeral",      "dafn marosimi"],
    ["funny",      "kulgili"],
    ["fur",      "mo'yna"],
    ["furniture",      "mebel"],
    ["further",      "bundan keyin"],
    ["furthest",      "eng uzoq"],
    ["future",      "kelajak"],
    ["g",      "g"],
    ["gain",      "daromad"],
    ["gallon",      "gallon"],
    ["gamble",      "qimor"],
    ["gambling",      "qimor"],
    ["game",      "o'yin"],
    ["gap",      "bo'shliq"],
    ["garage",      "garaj"],
    ["garbage",      "axlat"],
    ["garden",      "bog'"],
    ["gas",      "gaz"],
    ["gasoline",      "benzin"],
    ["gate",      "Darvoza"],
    ["gather",      "yig'ish"],
    ["gay",      "gey"],
    ["gear",      "tishli"],
    ["gene",      "gen"],
    ["general",      "umumiy"],
    ["generally",      "umuman"],
    ["generate",      "yaratish"],
    ["generation",      "avlod"],
    ["generous",      "saxiy"],
    ["gentle",      "yumshoq"],
    ["gentleman",      "janob"],
    ["gently",      "muloyimlik bilan"],
    ["genuine",      "haqiqiy"],
    ["geography",      "geografiya"],
    ["get",      "olish"],
    ["get along with",      "chiqishmoq"],
    ["get off",      "jo'nash"],
    ["giant",      "gigant"],
    ["gift",      "sovg'a"],
    ["girl",      "qiz"],
    ["girlfriend",      "qiz do'stim"],
    ["give",      "berish"],
    ["glad",      "hursandman"],
    ["glass",      "shisha"],
    ["global",      "global"],
    ["glove",      "qo'lqop"],
    ["glue",      "elim"],
    ["gm",      "gm"],
    ["go",      "bor"],
    ["goal",      "maqsad"],
    ["god",      "xudo"],
    ["gold",      "oltin"],
    ["good",      "yaxshi"],
    ["goodbye",      "Xayr. Salomat bo'ling"],
    ["goods",      "tovarlar"],
    ["govern",      "boshqarmoq"],
    ["government",      "hukumat"],
    ["governor",      "gubernator"],
    ["grab",      "ushlash"],
    ["grade",      "sinf"],
    ["gradual",      "asta-sekin"],
    ["gradually",      "asta-sekin"],
    ["graduate",      "bitiruvchi"],
    ["grain",      "don"],
    ["gram",      "gram"],
    ["grammar",      "grammatika"],
    ["grand",      "katta"],
    ["grandchild",      "nabira"],
    ["granddaughter",      "nabira"],
    ["grandfather",      "bobo"],
    ["grandmother",      "buvi"],
    ["grandparent",      "bobo va buvi"],
    ["habit",      "odat"],
    ["hair",      "Soch"],
    ["hairdresser",      "sartarosh"],
    ["half",      "yarim"],
    ["hall",      "zal"],
    ["hammer",      "bolg'a"],
    ["hand",      "qo'l"],
    ["handle",      "tutqich"],
    ["hang",      "osilib turish"],
    ["happen",      "sodir bo'lmoq"],
    ["happily",      "baxtli"],
    ["happy",      "baxtli"],
    ["hard",      "qattiq"],
    ["hardly",      "qiyin"],
    ["harm",      "zarar"],
    ["harmful",      "zararli"],
    ["harmless",      "zararsiz"],
    ["hat",      "shlyapa"],
    ["hate",      "nafrat"],
    ["hatred",      "nafrat"],
    ["have",      "bor"],
    ["have to",      "kerak"],
    ["he",      "u"],
    ["head",      "bosh"],
    ["headache",      "bosh og'rig'i"],
    ["heal",      "shifo"],
    ["health",      "salomatlik"],
    ["healthy",      "sog'lom"],
    ["hear",      "eshitish"],
    ["hear from",      "dan eshitish"],
    ["hear of",      "eshitish"],
    ["hearing",      "eshitish"],
    ["heart",      "yurak"],
    ["heat",      "issiqlik"],
    ["heating",      "isitish"],
    ["heaven",      "jannat"],
    ["heavily",      "og'ir"],
    ["heavy",      "og'ir"],
    ["heel",      "tovon"],
    ["height",      "balandlik"],
    ["hell",      "jahannam"],
    ["hello",      "Salom"],
    ["help",      "Yordam bering"],
    ["help out",      "yordamlashmoq"],
    ["helpful",      "foydali"],
    ["her",      "u"],
    ["here",      "Bu yerga"],
    ["hero",      "qahramon"],
    ["hers",      "uniki"],
    ["herself",      "o'zi"],
    ["hesitate",      "ikkilanish"],
    ["hi",      "salom"],
    ["hide",      "yashirish"],
    ["high",      "yuqori"],
    ["high school",      "o'rta maktab"],
    ["highlight",      "ta'kidlash"],
    ["highly",      "yuqori"],
    ["highway",      "magistral"],
    ["hill",      "tepalik"],
    ["him",      "u"],
    ["himself",      "o'zi"],
    ["hip",      "kestirib"],
    ["hire",      "ijaraga olish"],
    ["his",      "uning"],
    ["historical",      "tarixiy"],
    ["history",      "tarix"],
    ["hit",      "urish"],
    ["hobby",      "xobbi"],
    ["hold",      "tutmoq"],
    ["hold on",      "to'xtab tur"],
    ["hole",      "teshik"],
    ["holiday",      "bayram"],
    ["hollow",      "bo'shliq"],
    ["holy",      "muqaddas"],
    ["home",      "uy"],
    ["homework",      "uy vazifasi"],
    ["honest",      "halol"],
    ["honestly",      "halol"],
    ["honor",      "sharaf"],
    ["hook",      "kanca"],
    ["hope",      "umid"],
    ["hopefully",      "umid qilamanki"],
    ["horizontal",      "gorizontal"],
    ["horn",      "shox"],
    ["horror",      "dahshat"],
    ["horse",      "ot"],
    ["hospital",      "kasalxona"],
    ["host",      "mezbon"],
    ["hot",      "issiq"],
    ["hotel",      "mehmonxona"],
    ["hour",      "soat"],
    ["house",      "uy"],
    ["household",      "uy xo'jaligi"],
    ["housing",      "uy-joy"],
    ["how",      "Qanaqasiga"],
    ["however",      "ammo"],
    ["huge",      "katta"],
    ["human",      "inson"],
    ["humor",      "hazil"],
    ["humorous",      "hazil"],
    ["hungry",      "och"],
    ["hunt",      "ov"],
    ["hunting",      "ov"],
    ["hurry",      "shoshilinch"],
    ["hurt",      "jabr"],
    ["husband",      "er"],
    ["i.e.",      "ya'ni"],
    ["ice",      "muz"],
    ["ice cream",      "muzqaymoq"],
    ["idea",      "g'oya"],
    ["ideal",      "ideal"],
    ["identify",      "aniqlash"],
    ["identity",      "shaxsiyat"],
    ["if",      "agar"],
    ["ignore",      "e'tibor bermaslik"],
    ["ill",      "kasal"],
    ["illegal",      "noqonuniy"],
    ["illness",      "kasallik"],
    ["illustrate",      "tasvirlash"],
    ["image",      "tasvir"],
    ["imaginary",      "xayoliy"],
    ["imagination",      "tasavvur"],
    ["imagine",      "tasavvur qiling"],
    ["immediate",      "darhol"],
    ["immediately",      "darhol"],
    ["immoral",      "axloqsiz"],
    ["impact",      "ta'sir"],
    ["impatient",      "sabrsiz"],
    ["implication",      "ma'no"],
    ["imply",      "ishora qilish"],
    ["import",      "Import"],
    ["importance",      "ahamiyat"],
    ["important",      "muhim"],
    ["impose",      "qo'yish"],
    ["impossible",      "mumkin emas"],
    ["impress",      "taassurot qoldirish"],
    ["impressed",      "taassurot qoldirdi"],
    ["impression",      "taassurot"],
    ["impressive",      "ta'sirli"],
    ["improve",      "yaxshilash"],
    ["improvement",      "yaxshilash"],
    ["in",      "ichida"],
    ["inability",      "qobiliyatsizlik"],
    ["inch",      "dyuym"],
    ["incident",      "voqea"],
    ["include",      "o'z ichiga oladi"],
    ["including",      "shu jumladan"],
    ["income",      "daromad"],
    ["increase", "kattalashtirish"],
    ["increasingly", "borgan sari"],
    ["indeed", "haqiqatdan ham"],
    ["independence", "mustaqillik"],
    ["independent", "mustaqil"],
    ["index", "indeks"],
    ["indicate", "ko'rsatmoq"],
    ["indication", "ko'rsatma"],
    ["indirect", "bilvosita"],
    ["individual", "individual"],
    ["indoor", "ichki"],
    ["indoors", "ichki"],
    ["industrial", "sanoat"],
    ["industry", "sanoat"],
    ["inevitable", "muqarrar"],
    ["inevitably", "muqarrar"],
    ["infect", "yuqtirish"],
    ["infected", "kasallangan"],
    ["infection", "infektsiya"],
    ["infectious", "yuqumli"],
    ["influence", "ta'sir qilish"],
    ["inform", "xabar berish"],
    ["informal", "norasmiy"],
    ["information", "ma `lumot"],
    ["ingredient", "ingrediyent"],
    ["initial", "boshlang'ich"],
    ["initially", "dastlab"],
    ["initiative", "tashabbus"],
    ["injure", "jarohat qilish"],
    ["injured", "jarohatlangan"],
    ["injury", "jarohat"],
    ["ink", "siyoh"],
    ["inner", "ichki"],
    ["innocent", "aybsiz"],
    ["inquiry", "so'rov"],
    ["insect", "hasharot"],
    ["inside", "ichkarida"],
    ["insist", "talab qilish"],
    ["install", "o'rnatish"],
    ["instance", "misol"],
    ["instead", "o'rniga"],
    ["instead of", "o'rniga"],
    ["institute", "institut"],
    ["institution", "muassasa"],
    ["instruction", "ko'rsatma"],
    ["instrument", "asbob"],
    ["insult", "haqorat"],
    ["insulting", "haqorat"],
    ["insurance", "sug'urta"],
    ["intellectual", "intellektual"],
    ["intelligence", "razvedka"],
    ["intelligent", "aqlli"],
    ["intend", "niyat"],
    ["intended", "mo'ljallangan"],
    ["intense", "kuchli"],
    ["intention", "niyat"],
    ["interest", "qiziqish"],
    ["interested", "qiziqish"],
    ["interesting", "qiziqarli"],
    ["interior", "ichki"],
    ["internal", "ichki"],
    ["international", "xalqaro"],
    ["interpret", "talqin qilish"],
    ["interpretation", "tarjima"],
    ["interrupt", "to'xtatish"],
    ["interruption", "uzilish"],
    ["interval", "interval"],
    ["interview", "intervyu"],
    ["into", "ichiga"],
    ["introduce", "tanishtirmoq"],
    ["invent", "ixtiro"],
    ["invention", "kashfiyot"],
    ["invest", "investitsiya qilish"],
    ["investigate", "Tekshirish"],
    ["investigation", "tergov"],
    ["investment", "sarmoya"],
    ["invitation", "taklif"],
    ["invite", "taklif qilish"],
    ["involve", "jalb qilish"],
    ["involved", "jalb qilingan"],
    ["involvement", "ishtirok etish"],
    ["iron", "temir"],
    ["irritate", "g'azablanish"],
    ["irritated", "g'azablangan"],
    ["island", "orol"],
    ["issue", "nashr"],
    ["it", "bu"],
    ["item", "element"],
    ["its", "uning"],
    ["itself", "o'zi"],
    ["jacket", "ko'ylagi"],
    ["jail", "qamoq"],
    ["jealous", "rashkchi"],
    ["jeans", "jinsi shimlar"],
    ["jelly", "jele"],
    ["jewelry", "zargarlik buyumlari"],
    ["job", "ish"],
    ["join", "qo'shilish"],
    ["join in", "Qo'shilish"],
    ["joint", "qo'shma"],
    ["joke", "hazil"],
    ["journalist", "jurnalist"],
    ["journey", "sayohat"],
    ["joy", "quvonch"],
    ["judge", "sudya"],
    ["judgment", "hukm"],
    ["juice", "sharbat"],
    ["jump", "sakramoq"],
    ["junior", "kichik"],
    ["jury", "hakamlar hay'ati"],
    ["just", "shunchaki"],
    ["justice", "adolat"],
    ["justified", "oqlangan"],
    ["justify", "oqlash"],
    ["keen", "o'tkir"],
    ["keep", "saqlamoq"],
    ["keep out", "tashqari, ushlab qolish"],
    ["keep out of", "tashqarida turing"],
    ["key", "kalit"],
    ["keyboard", "klaviatura"],
    ["kick", "tepish"],
    ["kid", "bola"],
    ["kill", "o'ldirish"],
    ["killing", "o'ldirish"],
    ["kilogram", "kilogramm"],
    ["kilometer", "kilometr"],
    ["kind", "mehribon"],
    ["kindly", "mehribon"],
    ["kindness", "mehribonlik"],
    ["king", "shoh"],
    ["kiss", "o'pish"],
    ["kitchen", "oshxona"],
    ["km", "km"],
    ["knee", "tizza"],
    ["knife", "pichoq"],
    ["knock", "taqillatish"],
    ["knot", "tugun"],
    ["know", "bilaman"],
    ["knowledge", "bilim"],
    ["l", "l"],
    ["label", "yorliq"],
    ["labor", "mehnat"],
    ["laboratory", "laboratoriya"],
    ["lack", "etishmaslik"],
    ["lacking", "etishmaydi"],
    ["lady", "xonim"],
    ["lake", "ko'l"],
    ["lamp", "chiroq"],
    ["land", "yer"],
    ["landscape", "manzara"],
    ["lane", "bo'lak"],
    ["language", "til"],
    ["large", "katta"],
    ["largely", "asosan"],
    ["last 1", "oxirgi 1"],
    ["late", "kech"],
    ["lately", "so'nggi paytlarda"],
    ["later", "keyinroq"],
    ["latest", "oxirgi"],
    ["latter", "oxirgi"],
    ["laugh", "kulmoq"],
    ["launch", "Ishga tushirish"],
    ["laundry", "kir yuvish"],
    ["law", "qonun"],
    ["lawyer", "huquqshunos; advokat"],
    ["lay", "yotish"],
    ["layer", "qatlam"],
    ["lazy", "dangasa"],
    ["lead 1", "qo'rg'oshin 1"],
    ["leader", "rahbar"],
    ["leading 1", "etakchi 1"],
    ["leaf", "barg"],
    ["league", "liga"],
    ["lean", "ozg'in"],
    ["learn", "o'rganish"],
    ["least", "kamida"],
    ["leather", "teri"],
    ["leave", "ketmoq"],
    ["lecture", "leksiya"],
    ["left", "chap"],
    ["leg", "oyoq"],
    ["legal", "qonuniy"],
    ["lemon", "limon"],
    ["lend", "qarz berish"],
    ["length", "uzunlik"],
    ["less", "Ozroq"],
    ["lessen", "kamaytirish"],
    ["let", "qo'ying"],
    ["letter", "xat"],
    ["level", "Daraja"],
    ["liberal", "liberal"],
    ["library", "kutubxona"],
    ["license", "litsenziya"],
    ["lid", "qopqoq"],
    ["lie 1", "yolg'on 1"],
    ["life", "hayot"],
    ["lift", "ko'tarish"],
    ["light", "yorug'lik"],
    ["lightly", "engil"],
    ["like", "yoqdi"],
    ["likely", "ehtimol"],
    ["limit", "chegara"],
    ["limited", "cheklangan"],
    ["line", "chiziq"],
    ["link", "havola"],
    ["lip", "lab"],
    ["liquid", "suyuqlik"],
    ["list", "ro'yxat"],
    ["listen", "tingla"],
    ["liter", "litr"],
    ["literature", "adabiyot"],
    ["little", "biroz"],
    ["live 1", "jonli 1"],
    ["live 2", "jonli 2"],
    ["lively", "jonli"],
    ["living", "yashash"],
    ["load", "yuk"],
    ["loan", "qarz"],
    ["local", "mahalliy"],
    ["locate", "joylashish"],
    ["location", "Manzil"],
    ["lock", "qulf"],
    ["lock up", "Qulflamoq"],
    ["logic", "mantiq"],
    ["logical", "mantiqiy"],
    ["lonely", "yolg'iz"],
    ["long", "uzoq"],
    ["look", "qarash"],
    ["loose", "bo'sh"],
    ["loosely", "bo'sh"],
    ["lord", "lord"],
    ["lose", "yo'qotish"],
    ["loss", "yo'qotish"],
    ["lost", "yo'qolgan"],
    ["lot", "ko'p"],
    ["loud", "baland ovoz"],
    ["love", "sevgi"],
    ["lover", "sevgili"],
    ["low", "past"],
    ["lower 1", "pastki 1"],
    ["loyal", "sodiq"],
    ["luck", "omad"],
    ["lucky", "omadli"],
    ["lump", "bo'lak"],
    ["lunch", "tushlik"],
    ["lung", "o'pka"],
    ["machine", "mashina"],
    ["machinery", "mashinalar"],
    ["mad", "Telba"],
    ["magazine", "jurnal"],
    ["magic", "sehrli"],
    ["mail", "pochta"],
    ["main", "asosiy"],
    ["mainly", "asosan"],
    ["maintain", "qo'llab-quvvatlash"],
    ["major", "mayor"],
    ["majority", "ko'pchilik"],
    ["make", "qilish"],
    ["makeup", "grim surmoq, pardoz qilmoq; yasamoq, tuzmoq"],
    ["male", "erkak"],
    ["mall", "savdo markazi"],
    ["man", "kishi"],
    ["manage", "boshqarish"],
    ["management", "boshqaruv"],
    ["manager", "menejer"],
    ["manner", "tarz"],
    ["manufacture", "ishlab chiqarish"],
    ["manufacturer", "ishlab chiqaruvchi"],
    ["manufacturing", "ishlab chiqarish"],
    ["many", "ko'p"],
    ["map", "xarita"],
    ["march", "mart"],
    ["mark", "belgi"],
    ["market", "bozor"],
    ["marketing", "marketing"],
    ["marriage", "nikoh"],
    ["married", "uylangan"],
    ["marry", "uylanish"],
    ["mass", "massa"],
    ["massive", "katta"],
    ["master", "ustoz"],
    ["match", "mos"],
    ["matching", "mos"],
    ["mate", "do'st"],
    ["material", "material"],
    ["math", "matematika"],
    ["mathematics", "matematika"],
    ["matter", "materiya"],
    ["maximum", "maksimal"],
    ["maybe", "balki"],
    ["mayor", "hokim"],
    ["me", "men"],
    ["meal", "ovqat"],
    ["mean", "anglatadi"],
    ["meaning", "ma'no"],
    ["means", "demak"],
    ["meanwhile", "Ayni paytda"],
    ["measure", "o'lchov"],
    ["measurement", "o'lchov"],
    ["meat", "go'sht"],
    ["media", "ommaviy axborot vositalari"],
    ["medical", "tibbiy"],
    ["medicine", "dori"],
    ["medium", "o'rta"],
    ["meet", "uchrashuv"],
    ["meeting", "uchrashuv"],
    ["melt", "eritish"],
    ["member", "a'zo"],
    ["membership", "A'zolik"],
    ["memory", "xotira"],
    ["mental", "aqliy"],
    ["mentally", "aqliy"],
    ["mention", "zikr"],
    ["menu", "menyu"],
    ["mere", "shunchaki"],
    ["merely", "shunchaki"],
    ["mess", "tartibsizlik"],
    ["message", "xabar"],
    ["messy", "tartibsiz"],
    ["metal", "metall"],
    ["method", "usul"],
    ["mg", "mg"],
    ["mid-", "o'rta"],
    ["middle", "o'rta"],
    ["midnight", "yarim tun"],
    ["might", "mumkin"],
    ["mild", "yumshoq"],
    ["mile", "milya"],
    ["military", "harbiy"],
    ["milk", "sut"],
    ["milligram", "milligram"],
    ["millimeter", "millimetr"],
    ["mind", "aql"],
    ["mine", "meniki"],
    ["mineral", "mineral"],
    ["minimum", "eng kam"],
    ["minister", "vazir"],
    ["ministry", "vazirlik"],
    ["minor", "kichik"],
    ["minority", "ozchilik"],
    ["minute 1", "1-daqiqa"],
    ["mirror", "oyna"],
    ["miss", "sog'indim"],
    ["missing", "yo'qolgan"],
    ["mistake", "Xato"],
    ["mistaken", "xato"],
    ["mix", "aralash"],
    ["mixed", "aralashgan"],
    ["mixture", "aralash"],
    ["mobile", "mobil"],
    ["model", "model"],
    ["modern", "zamonaviy"],
    ["mom", "onam"],
    ["moment", "lahza"],
    ["money", "pul"],
    ["monitor", "monitor"],
    ["month", "oy"],
    ["mood", "kayfiyat"],
    ["moon", "oy"],
    ["moral", "ahloqiy"],
    ["morally", "axloqiy"],
    ["more", "Ko'proq"],
    ["moreover", "bundan tashqari"],
    ["morning", "ertalab"],
    ["most", "ko'p"],
    ["mostly", "asosan"],
    ["mother", "Ona"],
    ["motion", "harakat"],
    ["motor", "motor"],
    ["motorcycle", "mototsikl"],
    ["mount", "montaj"],
    ["mountain", "tog"],
    ["mouse", "sichqoncha"],
    ["mouth", "og'iz"],
    ["move", "harakat"],
    ["movement", "harakat"],
    ["movie", "film"],
    ["movie theater", "kino teatr"],
    ["moving", "harakat"],
    ["much", "ko'p"],
    ["mud", "loy"],
    ["multiply", "ko'paytirish"],
    ["murder", "qotillik"],
    ["muscle", "muskul"],
    ["museum", "muzey"],
    ["music", "musiqa"],
    ["musical", "musiqiy"],
    ["musician", "musiqachi"],
    ["must", "kerak"],
    ["my", "mening"],
    ["myself", "o'zim"],
    ["mysterious", "sirli"],
    ["mystery", "sir"],
    ["nail", "tirnoq"],
    ["naked", "yalang'och"],
    ["name", "ism"],
    ["narrow", "tor"],
    ["nation", "millat"],
    ["national", "milliy"],
    ["native", "mahalliy"],
    ["natural", "tabiiy"],
    ["naturally", "tabiiy"],
    ["nature", "tabiat"],
    ["navy", "dengiz floti"],
    ["near", "yaqin"],
    ["nearby", "yaqin"],
    ["nearly", "deyarli"],
    ["neat", "pokiza"],
    ["necessarily", "majburiy"],
    ["necessary", "zarur"],
    ["neck", "bo'yin"],
    ["need", "kerak"],
    ["needle", "igna"],
    ["negative", "salbiy"],
    ["neighbor", "qo'shni"],
    ["neighborhood", "Turar joy dahasi"],
    ["neither", "yo'q"],
    ["nephew", "jiyan"],
    ["nerve", "asab"],
    ["nervous", "asabiy"],
    ["nest", "uya"],
    ["net", "to'r"],
    ["network", "tarmoq"],
    ["never", "hech qachon"],
    ["nevertheless", "shunga qaramay"],
    ["new", "yangi"],
    ["newly", "Yangi"],
    ["news", "Yangiliklar"],
    ["newspaper", "gazeta"],
    ["next", "Keyingisi"],
    ["next to", "yonidagi"],
    ["nice", "yaxshi"],
    ["nicely", "yaxshi"],
    ["niece", "jiyan"],
    ["night", "tun"],
    ["no", "yo'q"],
    ["no one", "hech kim"],
    ["nobody", "hech kim"],
    ["nod", "bosh irg'adi"],
    ["noise", "shovqin"],
    ["noisy", "shovqinli"],
    ["non-", "bo'lmagan"],
    ["none", "hech"],
    ["nonsense", "bema'nilik"],
    ["nor", "na"],
    ["normal", "normal"],
    ["normally", "odatda"],
    ["north", "shimol"],
    ["northern", "shimoliy"],
    ["nose", "burun"],
    ["not", "yo'q"],
    ["note", "Eslatma"],
    ["nothing", "hech narsa"],
    ["notice", "xabar"],
    ["noticeable", "sezilarli"],
    ["notion", "tushuncha"],
    ["novel", "roman"],
    ["now", "hozir"],
    ["nowhere", "hech qayerda"],
    ["nuclear", "yadro"],
    ["number", "raqam"],
    ["numerous", "ko'p"],
    ["nurse", "hamshira"],
    ["nut", "yong'oq"],
    ["o'clock", "soat"],
    ["obey", "itoat eting"],
    ["object", "ob'ekt"],
    ["objective", "maqsad"],
    ["observation", "kuzatuv"],
    ["observe", "kuzatish"],
    ["obtain", "olish"],
    ["obvious", "aniq"],
    ["obviously", "aniq"],
    ["occasion", "foyda"],
    ["occasionally", "ba'zan"],
    ["occupied", "ishg'ol qilingan"],
    ["occupy", "egallash"],
    ["occur", "bo'ladi"],
    ["ocean", "okean"],
    ["odd", "g'alati"],
    ["oddly", "g'alati"],
    ["of", "ning"],
    ["off", "o'chirilgan"],
    ["offend", "xafa qilish"],
    ["offensive", "hujumkor"],
    ["offer", "taklif"],
    ["office", "idora"],
    ["officer", "ofitser"],
    ["official", "rasmiy"],
    ["officially", "rasmiy"],
    ["often", "ko'pincha"],
    ["oh", "oh"],
    ["oil", "moy"],
    ["old", "eski"],
    ["old-fashioned", "eski moda"],
    ["on", "yoqilgan"],
    ["once", "bir marta"],
    ["one", "bir"],
    ["one another", "bir-bir"],
    ["onion", "piyoz"],
    ["online", "onlayn"],
    ["only", "faqat"],
    ["onto", "to'g'ri"],
    ["open", "ochiq"],
    ["opening", "ochilish"],
    ["openly", "ochiq"],
    ["operate", "ishlash"],
    ["operation", "operatsiya"],
    ["opinion", "fikr"],
    ["opponent", "raqib"],
    ["opportunity", "imkoniyat"],
    ["oppose", "qarshi"],
    ["opposed", "qarshi"],
    ["opposing", "qarshi"],
    ["opposite", "qarama-qarshi"],
    ["opposition", "Muxolifat"],
    ["option", "variant"],
    ["or", "yoki"],
    ["orange", "apelsin"],
    ["order", "buyurtma"],
    ["ordinary", "oddiy"],
    ["organ", "organ"],
    ["organization", "tashkilot"],
    ["organize", "tashkil qilish"],
    ["organized", "uyushgan"],
    ["origin", "kelib chiqishi"],
    ["original", "asl"],
    ["originally", "aslida"],
    ["other", "boshqa"],
    ["otherwise", "aks holda"],
    ["ought to", "kerak"],
    ["ounce", "untsiya"],
    ["our", "bizning"],
    ["ours", "bizniki"],
    ["ourselves", "o'zimiz"],
    ["out", "tashqariga"],
    ["outdoor", "tashqi"],
    ["outdoors", "tashqarida"],
    ["outer", "tashqi"],
    ["outline", "kontur"],
    ["output", "chiqish"],
    ["outside", "tashqarida"],
    ["outstanding", "ajoyib"],
    ["oven", "pech"],
    ["over", "ustida"],
    ["overall", "umumiy"],
    ["overcome", "engish"],
    ["overseas", "chet elda"],
    ["owe", "qarz"],
    ["own", "Shaxsiy"],
    ["own up", "egalik qilish"],
    ["owner", "egasi"],
    ["p", "p"],
    ["p.m.", "p.m."],
    ["pace 1", "tezlik 1"],
    ["pack", "paket"],
    ["package", "paket"],
    ["page", "sahifa"],
    ["pain", "og'riq"],
    ["painful", "alamli"],
    ["paint", "bo'yamoq"],
    ["painter", "rassom"],
    ["painting", "rasm"],
    ["pair", "juftlik"],
    ["palace", "saroy"],
    ["pale", "oq rang"],
    ["pan", "pan"],
    ["panel", "panel"],
    ["pants", "shim"],
    ["paper", "qog'oz"],
    ["parallel", "parallel"],
    ["parent", "ota-ona"],
    ["park", "park"],
    ["parliament", "parlament"],
    ["part", "qism"],
    ["participate", "ishtirok etish"],
    ["particular", "alohida"],
    ["particularly", "ayniqsa"],
    ["partly", "qisman"],
    ["partner", "sherik"],
    ["partnership", "sheriklik"],
    ["party", "partiya"],
    ["pass", "o'tish"],
    ["passage", "o'tish"],
    ["passenger", "yo'lovchi"],
    ["passing", "o'tish"],
    ["passion", "ehtiros"],
    ["passport", "pasport"],
    ["past", "o'tmish"],
    ["path", "yo'l"],
    ["patience", "sabr"],
    ["patient", "bemor"],
    ["pattern", "naqsh"],
    ["pause", "pauza"],
    ["pay", "to'lash"],
    ["pay back", "qaytarib to'lash"],
    ["payment", "to'lov"],
    ["peace", "tinchlik"],
    ["peaceful", "tinch"],
    ["peak", "cho'qqi"],
    ["pen", "qalam"],
    ["penalty", "penalti"],
    ["pencil", "qalam"],
    ["people", "odamlar"],
    ["pepper", "qalapmir"],
    ["per", "boshiga"],
    ["percent", "foiz"],
    ["percentage", "foiz"],
    ["perfect", "mukammal"],
    ["perfectly", "Mukammal"],
    ["perform", "bajarish"],
    ["performance", "ishlash"],
    ["performer", "ijrochi"],
    ["perhaps", "balki"],
    ["period", "davr"],
    ["permanent", "doimiy"],
    ["permission", "ruxsat"],
    ["permit", "ruxsat"],
    ["person", "odam"],
    ["personal", "shaxsiy"],
    ["personality", "shaxsiyat"],
    ["personally", "shaxsan"],
    ["perspective", "perspektiv"],
    ["persuade", "ishontirish"],
    ["pet", "Uy hayvoni"],
    ["phase", "faza"],
    ["philosophy", "falsafa"],
    ["phone", "telefon"],
    ["photo", "fotosurat"],
    ["photocopy", "fotokopiya"],
    ["photograph", "fotosurat"],
    ["photographer", "fotosuratchi"],
    ["photography", "fotosurat"],
    ["phrase", "ibora"],
    ["physical", "jismoniy"],
    ["physically", "jismoniy"],
    ["physics", "fizika"],
    ["piano", "pianino"],
    ["pick", "tanlash"],
    ["picture", "rasm"],
    ["piece", "parcha"],
    ["pig", "cho'chqa"],
    ["pile", "qoziq"],
    ["pill", "hap"],
    ["pilot", "uchuvchi"],
    ["pin", "pin"],
    ["pink", "pushti"],
    ["pint", "pint"],
    ["pipe", "quvur"],
    ["pitch", "ohang"],
    ["place", "joy"],
    ["plain", "oddiy"],
    ["plan", "reja"],
    ["plane", "samolyot"],
    ["planet", "sayyora"],
    ["planning", "rejalashtirish"],
    ["plant", "o'simlik"],
    ["plastic", "plastik"],
    ["plate", "plastinka"],
    ["platform", "platforma"],
    ["play", "o'yin"],
    ["player", "o'yinchi"],
    ["pleasant", "yoqimli"],
    ["please", "Iltimos"],
    ["pleased", "hursandman"],
    ["pleasure", "zavq"],
    ["plenty", "ko'p"],
    ["plot", "syujet"],
    ["plug", "vilka"],
    ["plug in", "ulang"],
    ["plus 1", "ortiqcha 1"],
    ["pocket", "cho'ntak"],
    ["poem", "she'r"],
    ["poetry", "she'r"],
    ["point", "nuqta"],
    ["pointed", "ishorali"],
    ["poison", "zahar"],
    ["poisonous", "zaharli"],
    ["pole", "qutb"],
    ["police", "politsiya"],
    ["policy", "siyosat"],
    ["polish", "polyak"],
    ["polite", "odobli"],
    ["political", "siyosiy"],
    ["politically", "siyosiy"],
    ["politician", "siyosatchi"],
    ["politics", "siyosat"],
    ["pollution", "ifloslanish"],
    ["pool", "hovuz"],
    ["poor", "kambag'al"],
    ["pop", "pop"],
    ["popular", "mashhur"],
    ["population", "aholi"],
    ["port", "port"],
    ["pose", "poza"],
    ["position", "pozitsiya"],
    ["positive", "ijobiy"],
    ["possess", "egalik"],
    ["possession", "egalik"],
    ["possibility", "mumkin"],
    ["possible", "mumkin"],
    ["possibly", "ehtimol"],
    ["post", "post"],
    ["post office", "pochta"],
    ["pot", "qozon"],
    ["potato", "kartoshka"],
    ["potential", "potentsial"],
    ["pound", "funt"],
    ["pour", "to'kish"],
    ["poverty", "qashshoqlik"],
    ["powder", "chang"],
    ["power", "kuch"],
    ["powerful", "kuchli"],
    ["practical", "amaliy"],
    ["practically", "amalda"],
    ["practice", "amaliyot"],
    ["praise", "Maqtov"],
    ["prayer", "ibodat"],
    ["precise", "aniq"],
    ["precisely", "aniq"],
    ["predict", "bashorat"],
    ["prefer", "afzal"],
    ["preference", "afzal"],
    ["pregnant", "homilador"],
    ["premises", "bino"],
    ["preparation", "tayyorlash"],
    ["prepare", "tayyorlash"],
    ["prepared", "tayyorlangan"],
    ["presence", "mavjudlik"],
    ["present", "hozir"],
    ["presentation", "taqdimot"],
    ["preserve", "saqlash"],
    ["president", "Prezident"],
    ["press", "bosish"],
    ["pressure", "bosim"],
    ["presumably", "ehtimol"],
    ["pretend", "go'yo"],
    ["pretty", "chiroyli"],
    ["prevent", "oldini olish"],
    ["previous", "oldingi"],
    ["previously", "ilgari"],
    ["price", "narx"],
    ["pride", "g'urur"],
    ["priest", "ruhoniy"],
    ["primarily", "birinchi navbatda"],
    ["primary", "asosiy"],
    ["prime minister", "Bosh Vazir"],
    ["prince", "shahzoda"],
    ["princess", "malika"],
    ["principal", "asosiy"],
    ["principle", "prinsip"],
    ["print", "chop etish"],
    ["printer", "printer"],
    ["prior", "oldin"],
    ["priority", "ustunlik"],
    ["prison", "qamoq"],
    ["prisoner", "mahbus"],
    ["private", "xususiy"],
    ["prize", "mukofot"],
    ["probably", "ehtimol"],
    ["problem", "muammo"],
    ["procedure", "protsedura"],
    ["proceed", "davom etish"],
    ["process 1", "1-jarayon"],
    ["produce", "mahsulot"],
    ["producer", "ishlab chiqaruvchi"],
    ["product", "mahsulot"],
    ["production", "ishlab chiqarish"],
    ["profession", "kasb"],
    ["professional", "professional"],
    ["professor", "professor"],
    ["profile", "profil"],
    ["profit", "foyda"],
    ["progress", "taraqqiyot"],
    ["project", "loyiha"],
    ["promise", "va'da"],
    ["promote", "rag'batlantirish"],
    ["promotion", "rag'batlantirish"],
    ["prompt", "tezkor"],
    ["promptly", "zudlik bilan"],
    ["pronounce", "talaffuz"],
    ["pronunciation", "talaffuz"],
    ["proof", "dalil"],
    ["proper", "to'g'ri"],
    ["property", "mulk"],
    ["proportion", "nisbat"],
    ["proposal", "taklif"],
    ["propose", "taklif qilish"],
    ["prospect", "istiqbol"],
    ["protect", "himoya qilish"],
    ["protection", "himoya"],
    ["protest", "norozilik"],
    ["proud", "g'urur"],
    ["proudly", "g'urur bilan"],
    ["prove", "isbotlash"],
    ["provide", "ta'minlash"],
    ["provided", "ta'minlangan"],
    ["pt.", "pt."],
    ["public", "ommaviy"],
    ["publication", "nashr"],
    ["publicity", "ommaviylik"],
    ["publish", "nashr qilish"],
    ["publishing", "nashr qilish"],
    ["pull", "Torting"],
    ["punch", "musht"],
    ["punish", "jazolash"],
    ["punishment", "jazo"],
    ["purchase", "sotib olish"],
    ["pure", "toza"],
    ["purely", "toza"],
    ["purple", "siyohrang"],
    ["purpose", "maqsad"],
    ["pursue", "ta'qib qilish"],
    ["push", "Durang"],
    ["put", "qo'yish"],
    ["qualification", "malaka"],
    ["qualified", "malakali"],
    ["qualify", "saralash"],
    ["quality", "sifat"],
    ["quantity", "miqdori"],
    ["quarter", "chorak"],
    ["queen", "malika"],
    ["question", "savol"],
    ["quick", "tezkor"],
    ["quickly", "tezda"],
    ["quiet", "sokin"],
    ["quite", "juda"],
    ["quote", "iqtibos"],
    ["race", "poyga"],
    ["racing", "poyga"],
    ["radio", "radio"],
    ["rail", "temir"],
    ["railroad", "temir yo'l"],
    ["rain", "yomg'ir"],
    ["raise", "oshirish"],
    ["range", "diapazon"],
    ["rank", "darajali"],
    ["rapid", "tezkor"],
    ["rare", "kamdan-kam"],
    ["rarely", "kamdan-kam hollarda"],
    ["rate", "stavka"],
    ["rather", "aniqroq"],
    ["raw", "xom"],
    ["re-", "qayta"],
    ["reach", "etish"],
    ["react", "reaktsiya"],
    ["reaction", "reaktsiya"],
    ["read", "o'qish"],
    ["reader", "o'quvchi"],
    ["reading", "o'qish"],
    ["ready", "tayyor"],
    ["real", "haqiqiy"],
    ["realistic", "haqiqiy"],
    ["reality", "haqiqat"],
    ["realize", "tushunish"],
    ["really", "haqiqatan"],
    ["rear", "orqa"],
    ["reason", "sabab"],
    ["reasonable", "oqilona"],
    ["reasonably", "oqilona"],
    ["recall", "eslash"],
    ["receipt", "kvitansiya"],
    ["receive", "qabul qilish"],
    ["recent", "yaqinda"],
    ["recently", "yaqinda"],
    ["reception", "qabul qilish"],
    ["recognition", "tan olish"],
    ["recognize", "tan olish"],
    ["recommend", "tavsiya qilaman"],
    ["recommendation", "tavsiya"],
    ["record", "rekord"],
    ["recording", "yozuv"],
    ["recover", "tiklash"],
    ["recovery", "tiklanish"],
    ["red", "qizil"],
    ["reduce", "kamaytirish"],
    ["reduction", "kamaytirish"],
    ["refer", "murojaat"],
    ["reference", "ma'lumotnoma"],
    ["reflect", "aks ettirish"],
    ["reform", "islohot"],
    ["refrigerator", "muzlatgich"],
    ["refusal", "rad etish"],
    ["refuse 1", "rad etish 1"],
    ["regard", "Hurmat"],
    ["regarding", "to'g'risida"],
    ["region", "mintaqa"],
    ["regional", "mintaqaviy"],
    ["register", "ro'yxatdan o'tish"],
    ["regret", "afsus"],
    ["regular", "muntazam"],
    ["regularly", "muntazam ravishda"],
    ["regulation", "tartibga solish"],
    ["reject", "rad etish"],
    ["relate", "bog'liq"],
    ["related", "bog'liq"],
    ["relation", "munosabat"],
    ["relationship", "munosabatlar"],
    ["relative", "qarindosh"],
    ["relatively", "nisbatan"],
    ["relax", "Rohatlaning"],
    ["relaxed", "xotirjam"],
    ["relaxing", "dam olish"],
    ["release", "ozod qilish"],
    ["relevant", "muvofiq"],
    ["relief", "yengillik"],
    ["religion", "din"],
    ["religious", "diniy"],
    ["rely", "ishonish"],
    ["remain", "qolish"],
    ["remaining", "qolgan"],
    ["remains", "qoladi"],
    ["remark", "eslatma"],
    ["remarkable", "e'tiborli"],
    ["remember", "eslab qoling"],
    ["remind", "eslatma"],
    ["remote", "masofadan"],
    ["removal", "olib tashlash"],
    ["remove", "olib tashlash"],
    ["rent", "ijara"],
    ["repair", "ta'mirlash"],
    ["repeat", "takrorlash"],
    ["repeated", "takroriy"],
    ["replace", "almashtirish"],
    ["reply", "javob berish"],
    ["report", "hisobot"],
    ["reporter", "muxbir"],
    ["represent", "vakillik qilish"],
    ["representative", "vakil"],
    ["reproduce", "ko'paytirish"],
    ["reputation", "obro'"],
    ["request", "so'rov"],
    ["require", "talab qilish"],
    ["requirement", "talab"],
    ["rescue", "qutqarish"],
    ["research", "tadqiqot"],
    ["reservation", "rezervatsiya"],
    ["reserve", "zaxira"],
    ["resident", "rezident"],
    ["resist", "qarshilik"],
    ["resistance", "qarshilik"],
    ["resolve", "hal qilish"],
    ["resort", "kurort"],
    ["resource", "manba"],
    ["respect", "hurmat"],
    ["respond", "javob berish"],
    ["response", "javob"],
    ["responsibility", "mas'uliyat"],
    ["responsible", "mas'uliyatli"],
    ["rest", "dam olish"],
    ["restaurant", "restoran"],
    ["restore", "tiklash"],
    ["restrict", "cheklash"],
    ["restricted", "cheklangan"],
    ["restriction", "cheklov"],
    ["result", "natija"],
    ["retain", "ushlab turish"],
    ["retire", "nafaqaga chiqish"],
    ["retired", "nafaqaga chiqqan"],
    ["retirement", "iste'fo"],
    ["return", "qaytish"],
    ["reveal", "oshkor qilish"],
    ["reverse", "teskari"],
    ["review", "ko'rib chiqish"],
    ["revise", "qayta ko'rib chiqish"],
    ["revision", "qayta ko'rib chiqish"],
    ["revolution", "inqilob"],
    ["reward", "mukofot"],
    ["rhythm", "ritm"],
    ["rice", "guruch"],
    ["rich", "boy"],
    ["rid", "qutilish"],
    ["ride", "yurish"],
    ["rider", "chavandoz"],
    ["ridiculous", "kulgili"],
    ["riding", "ot minish"],
    ["right", "o'ng"],
    ["rightly", "to'g'ri"],
    ["ring 1", "1-ring"],
    ["rise", "ko'tarilish"],
    ["risk", "xavf"],
    ["rival", "raqib"],
    ["river", "daryo"],
    ["road", "yo'l"],
    ["rob", "o'g'irlash"],
    ["rock", "tosh"],
    ["role", "rol"],
    ["roll", "rulo"],
    ["romantic", "romantik"],
    ["roof", "tom"],
    ["room", "xona"],
    ["root", "ildiz"],
    ["rope", "arqon"],
    ["rose", "atirgul"],
    ["rough", "qo'pol"],
    ["roughly", "taxminan"],
    ["round", "dumaloq"],
    ["route", "marshrut"],
    ["routine", "muntazam"],
    ["row", "qator"],
    ["royal", "qirollik"],
    ["rub", "ishqalash"],
    ["rubber", "kauchuk"],
    ["rude", "qo'pol"],
    ["rudely", "qo'pol"],
    ["ruin", "xarob"],
    ["ruined", "buzilgan"],
    ["rule", "qoida"],
    ["ruler", "hukmdor"],
    ["rumor", "mish-mish"],
    ["run", "yugurish"],
    ["runner", "yuguruvchi"],
    ["running", "yugurish"],
    ["rural", "qishloq"],
    ["rush", "shoshilinch"],
    ["sack", "qop"],
    ["sad", "afsus"],
    ["sadly", "afsuski"],
    ["sadness", "qayg'u"],
    ["safe", "xavfsiz"],
    ["safely", "xavfsiz"],
    ["safety", "xavfsizlik"],
    ["sail", "yelkan"],
    ["sailing", "yelkan"],
    ["sailor", "dengizchi"],
    ["salad", "salat"],
    ["salary", "ish haqi"],
    ["sale", "sotish"],
    ["salt", "tuz"],
    ["salty", "sho'r"],
    ["same", "bir xil"],
    ["sample", "namuna"],
    ["sand", "qum"],
    ["satisfaction", "qoniqish"],
    ["satisfied", "qoniqarli"],
    ["satisfy", "qoniqish"],
    ["satisfying", "qoniqarli"],
    ["sauce", "sous"],
    ["save", "saqlash"],
    ["saving", "saqlash"],
    ["say", "demoq"],
    ["scale", "shkala"],
    ["scare", "qo'rqitish"],
    ["scared", "qo'rqqan"],
    ["scary", "qo'rqinchli"],
    ["scene", "sahna"],
    ["schedule", "jadval"],
    ["school", "maktab"],
    ["science", "fan"],
    ["scientific", "ilmiy"],
    ["scientist", "olim"],
    ["scissors", "qaychi"],
    ["score", "Xol"],
    ["scratch", "chizish"],
    ["scream", "qichqiriq"],
    ["screen", "ekran"],
    ["screw", "vida"],
    ["sea", "dengiz"],
    ["seal", "muhr"],
    ["search", "qidirmoq"],
    ["season", "mavsum"],
    ["seat", "o'rindiq"],
    ["second", "ikkinchi"],
    ["secondary", "ikkinchi darajali"],
    ["secret", "sir"],
    ["secretary", "kotib"],
    ["section", "Bo'lim"],
    ["sector", "sektor"],
    ["secure", "xavfsiz"],
    ["security", "xavfsizlik"],
    ["see", "ko'rish"],
    ["seed", "urug'"],
    ["seek", "izlash"],
    ["seem", "ko'rinadi"],
    ["select", "tanlash"],
    ["selection", "tanlash"],
    ["self", "o'zini"],
    ["self-", "o'z-o'zini"],
    ["sell", "sotish"],
    ["semester", "semestr"],
    ["senate", "senat"],
    ["senator", "senator"],
    ["send", "yuborish"],
    ["senior", "katta"],
    ["sense", "his"],
    ["sensible", "aqlli"],
    ["sensitive", "sezgir"],
    ["sentence", "jumla"],
    ["separate", "alohida"],
    ["separated", "ajratilgan"],
    ["separately", "alohida"],
    ["separation", "ajralish"],
    ["series", "seriya"],
    ["serious", "jiddiy"],
    ["seriously", "jiddiy"],
    ["servant", "xizmatkor"],
    ["serve", "xizmat qilish"],
    ["service", "xizmat"],
    ["session", "sessiya"],
    ["set", "to'siq"],
    ["settle", "joylashish"],
    ["several", "bir nechta"],
    ["severe", "og'ir"],
    ["sew", "tikish"],
    ["sex", "jinsiy aloqa"],
    ["sexual", "jinsiy"],
    ["shade", "soya"],
    ["shadow", "soya"],
    ["shake", "silkitish"],
    ["shall", "bo'ladi"],
    ["shallow", "sayoz"],
    ["shame", "uyat"],
    ["shape", "shakl"],
    ["shaped", "shaklli"],
    ["share", "ulashish"],
    ["sharp", "o'tkir"],
    ["sharply", "keskin"],
    ["shave", "soqol olish"],
    ["she", "u"],
    ["sheep", "qo'y"],
    ["sheet", "varaq"],
    ["shelf", "javon"],
    ["shell", "qobiq"],
    ["shelter", "boshpana"],
    ["shift", "shift"],
    ["shine", "porlash"],
    ["shiny", "porloq"],
    ["ship", "kema"],
    ["shirt", "ko'ylak"],
    ["shock", "shok"],
    ["shocking", "hayratlantiruvchi"],
    ["shoe", "poyabzal"],
    ["shoot", "otish"],
    ["shooting", "otishma"],
    ["shop", "do'kon"],
    ["shopping", "xarid qilish"],
    ["short", "qisqa"],
    ["shortly", "qisqa"],
    ["shot", "otish"],
    ["should", "kerak"],
    ["shoulder", "elka"],
    ["shout", "baqir"],
    ["show", "ko'rsatish"],
    ["shower", "dush"],
    ["shut", "yopiq"],
    ["shut down", "o'chirish; yopish"],
    ["shy", "uyatchan"],
    ["sick", "kasal"],
    ["side", "yon"],
    ["sideways", "yon tomonga"],
    ["sight", "ko'rish"],
    ["sign", "belgi"],
    ["signal", "signal"],
    ["signature", "imzo"],
    ["significant", "muhim"],
    ["significantly", "sezilarli"],
    ["silence", "jim"],
    ["silent", "jim"],
    ["silk", "ipak"],
    ["silly", "ahmoq"],
    ["silver", "kumush"],
    ["similar", "o'xshash"],
    ["similarly", "xuddi shunday"],
    ["simple", "oddiy"],
    ["simply", "shunchaki"],
    ["since", "bundan buyon"],
    ["sincere", "samimiy"],
    ["sincerely", "Hurmat bilan"],
    ["sing", "qo'shiq"],
    ["singer", "ashulachi"],
    ["singing", "qo'shiq aytish"],
    ["single", "yakka"],
    ["sink", "cho'kish"],
    ["sir", "janob"],
    ["sister", "singlim"],
    ["sit", "o'tirish"],
    ["sit down", "O'tir"],
    ["site", "sayt"],
    ["situation", "vaziyat"],
    ["size", "hajmi"],
    ["skill", "mahorat"],
    ["skilled", "malakali"],
    ["skillful", "mohir"],
    ["skin", "teri"],
    ["skirt", "yubka"],
    ["sky", "osmon"],
    ["sleep", "uyqu"],
    ["sleeve", "yeng"],
    ["slice", "tilim"],
    ["slide", "slayd"],
    ["slight", "engil"],
    ["slightly", "bir oz"],
    ["slip", "slip"],
    ["slope", "qiyalik"],
    ["slow", "sekin"],
    ["slowly", "sekin"],
    ["small", "kichik"],
    ["smart", "aqlli"],
    ["smash", "zarba"],
    ["smell", "hid"],
    ["smile", "tabassum"],
    ["smoke", "tutun"],
    ["smoking", "chekish"],
    ["smooth", "silliq"],
    ["smoothly", "silliq"],
    ["snake", "ilon"],
    ["snow", "qor"],
    ["so", "shunday"],
    ["soap", "sovun"],
    ["social", "ijtimoiy"],
    ["society", "jamiyat"],
    ["sock", "paypoq"],
    ["soft", "yumshoq"],
    ["softly", "yumshoqlik bilan"],
    ["software", "dasturiy ta'minot"],
    ["soil", "tuproq"],
    ["soldier", "askar"],
    ["solid", "qattiq"],
    ["solution", "yechim"],
    ["solve", "hal qilish"],
    ["some", "biroz"],
    ["somebody", "kimdir"],
    ["somehow", "qandaydir"],
    ["something", "nimadur"],
    ["sometimes", "ba'zan"],
    ["somewhat", "biroz"],
    ["somewhere", "bir joyda"],
    ["son", "o'g'lim"],
    ["song", "Qo'shiq"],
    ["soon", "yaqinda"],
    ["sore", "og'riq"],
    ["sorry", "kechirasiz"],
    ["sort", "saralash"],
    ["soul", "jon"],
    ["sound", "ovoz"],
    ["soup", "sho'rva"],
    ["sour", "nordon"],
    ["source", "manba"],
    ["south", "janubiy"],
    ["southern", "Janubiy"],
    ["space", "kosmos"],
    ["spare", "zaxira"],
    ["speak", "gapirish"],
    ["speaker", "ma'ruzachi"],
    ["special", "maxsus"],
    ["specialist", "mutaxassis"],
    ["specially", "maxsus"],
    ["species", "turlar"],
    ["specific", "maxsus"],
    ["specifically", "ayniqsa"],
    ["speech", "nutq"],
    ["speed", "tezlik"],
    ["speed up", "tezlikni oshirmoq"],
    ["spell", "jodu"],
    ["spelling", "imlo"],
    ["spend", "sarflash"],
    ["spice", "ziravorlar"],
    ["spicy", "achchiq"],
    ["spider", "o'rgimchak"],
    ["spill", "to'kish"],
    ["spin", "aylantirish"],
    ["spirit", "ruh"],
    ["spiritual", "ruhiy"],
    ["spite", "g'azab"],
    ["split", "Split"],
    ["split up", "ajralish"],
    ["spoil", "buzish"],
    ["spoken", "gapirish"],
    ["spoon", "qoshiq"],
    ["sport", "sport"],
    ["spot", "nuqta"],
    ["spray", "sprey"],
    ["spread", "tarqalish"],
    ["spring", "bahor"],
    ["square", "kvadrat"],
    ["squeeze", "siqish"],
    ["stable", "barqaror"],
    ["staff", "xodimlar"],
    ["stage", "bosqich"],
    ["stair", "zinapoya"],
    ["stamp", "shtamp"],
    ["stand", "turish"],
    ["stand up", "o'rningizdan turing"],
    ["standard", "standart"],
    ["star", "Yulduz"],
    ["stare", "qarash"],
    ["start", "boshlash"],
    ["start up", "ish boshlash"],
    ["state", "davlat"],
    ["statement", "bayonot"],
    ["station", "stansiya"],
    ["statue", "haykal"],
    ["status", "holat"],
    ["stay", "qoling"],
    ["steady", "barqaror"],
    ["steal", "o'g'irlash"],
    ["steam", "bug '"],
    ["steel", "po'lat"],
    ["steep", "tik"],
    ["steer", "boshqaruv"],
    ["step", "qadam"],
    ["stick", "tayoq"],
    ["stick out", "chiqish"],
    ["stick together", "birga yopishish"],
    ["sticky", "yopishqoq"],
    ["stiff", "qattiq"],
    ["still", "hali"],
    ["sting", "qichitish"],
    ["stir", "aralashtirish"],
    ["stock", "Aksiya"],
    ["stomach", "oshqozon"],
    ["stone", "tosh"],
    ["stop", "STOP"],
    ["store", "do'kon"],
    ["storm", "bo'ron"],
    ["story", "hikoya"],
    ["stove", "pechka"],
    ["straight", "Streyt"],
    ["strain", "kuchlanish"],
    ["strange", "g'alati"],
    ["strangely", "g'alati"],
    ["stranger", "begona"],
    ["strategy", "strategiya"],
    ["stream", "oqim"],
    ["street", "ko'cha"],
    ["strength", "kuch"],
    ["stress", "stress"],
    ["stressed", "ta'kidlangan"],
    ["stretch", "cho'zish"],
    ["strict", "qat'iy"],
    ["strictly", "qat'iy"],
    ["strike", "zarba"],
    ["striking", "zarbali"],
    ["string", "string"],
    ["strip", "chiziq"],
    ["stripe", "chiziq"],
    ["striped", "chiziqli"],
    ["stroke", "qon tomir"],
    ["strong", "kuchli"],
    ["structure", "tuzilma"],
    ["struggle", "kurash"],
    ["student", "talaba"],
    ["studio", "studiya"],
    ["study", "o'qish"],
    ["stuff", "narsalar"],
    ["stupid", "ahmoq"],
    ["style", "uslub"],
    ["subject", "Mavzu"],
    ["substance", "modda"],
    ["substantial", "asosiy"],
    ["substantially", "asosan"],
    ["substitute", "o'rnini bosuvchi"],
    ["succeed", "muvaffaqiyatli"],
    ["success", "muvaffaqiyat"],
    ["successful", "omadli"],
    ["such", "bunday"],
    ["suck", "emizish"],
    ["sudden", "to'satdan"],
    ["suddenly", "to'satdan"],
    ["suffer", "azob chekish"],
    ["suffering", "azob"],
    ["sufficient", "etarli"],
    ["sugar", "shakar"],
    ["suggest", "taklif qilish"],
    ["suggestion", "taklif"],
    ["suit", "kostyum"],
    ["suitable", "mos"],
    ["sum", "sum"],
    ["summary", "xulosa"],
    ["summer", "yoz"],
    ["sun", "quyosh"],
    ["superior", "yuqori"],
    ["supermarket", "Supermarket"],
    ["supply", "ta'minot"],
    ["support", "qo'llab-quvvatlash"],
    ["supporter", "qo'llab-quvvatlovchi"],
    ["suppose", "deylik"],
    ["sure", "albatta"],
    ["surely", "albatta"],
    ["surface", "yuza"],
    ["surgery", "jarrohlik"],
    ["surprise", "syurpriz"],
    ["surprised", "hayratlangan"],
    ["surprising", "hayratlanarli"],
    ["surround", "atrof"],
    ["surrounding", "atrof"],
    ["surroundings", "atrof-muhit"],
    ["survey", "tadqiqot"],
    ["survive", "omon qolish"],
    ["suspect", "shubhali"],
    ["suspect", "gumon"],
    ["suspicion", "shubha"],
    ["suspicious", "shubhali"],
    ["swallow", "qaldirg'och"],
    ["swear", "qasamyod"],
    ["sweat", "ter"],
    ["sweater", "sviter"],
    ["sweep", "supurish"],
    ["sweet", "shirin"],
    ["swell", "shish"],
    ["swelling", "shish"],
    ["swim", "suzish"],
    ["swimming", "suzish"],
    ["swimming pool", "suzish havzasi"],
    ["swing", "belanchak"],
    ["switch", "almashtirish"],
    ["swollen", "shishgan"],
    ["symbol", "ramz"],
    ["sympathetic", "rahmdil"],
    ["sympathy", "hamdardlik"],
    ["system", "tizim"],
    ["table", "stol"],
    ["tablet", "planshet"],
    ["tackle", "hal qilish"],
    ["tail", "dum"],
    ["take", "olish"],
    ["tale", "ertak"],
    ["talent", "iste'dod"],
    ["talk", "gaplash"],
    ["tall", "baland"],
    ["tank", "tank"],
    ["tap", "bosish"],
    ["tape", "lenta"],
    ["target", "maqsad"],
    ["task", "vazifa"],
    ["taste", "ta'm"],
    ["tax", "soliq"],
    ["taxi", "taksi"],
    ["tea", "choy"],
    ["teach", "o'rgatish"],
    ["teacher", "o'qituvchi"],
    ["teaching", "ta'lim"],
    ["team", "jamoa"],
    ["tear 1", "ko'z yoshi 1"],
    ["tear 2", "ko'z yoshi 2"],
    ["technical", "texnik"],
    ["technique", "texnika"],
    ["technology", "texnologiya"],
    ["telephone", "telefon"],
    ["television", "televizor"],
    ["tell", "ayt"],
    ["tell off", "ayting"],
    ["temperature", "harorat"],
    ["temporary", "vaqtinchalik"],
    ["tend", "moyil"],
    ["tendency", "moyillik"],
    ["tension", "kuchlanish"],
    ["tent", "chodir"],
    ["term", "muddati"],
    ["terrible", "qo'rqinchli"],
    ["terribly", "dahshatli"],
    ["territory", "hudud"],
    ["terror", "terror"],
    ["terrorism", "terrorizm"],
    ["terrorist", "terrorchi"],
    ["test", "sinov"],
    ["text", "matn"],
    ["than", "dan ko'ra"],
    ["thank", "rahmat"],
    ["thank you", "rahmat"],
    ["thanks", "rahmat"],
    ["that", "bu"],
    ["the", "the"],
    ["theater", "teatr"],
    ["their", "ularning"],
    ["theirs", "ularniki"],
    ["them", "ular"],
    ["theme", "mavzu"],
    ["themselves", "o'zlari"],
    ["then", "keyin"],
    ["theory", "nazariya"],
    ["there", "U yerda"],
    ["therefore", "shuning uchun"],
    ["they", "ular"],
    ["thick", "qalin"],
    ["thickly", "qalin"],
    ["thickness", "qalinligi"],
    ["thief", "o'g'ri"],
    ["thin", "nozik"],
    ["thing", "narsa"],
    ["think", "o'ylayman"],
    ["thinking", "fikrlash"],
    ["thirsty", "chanqagan"],
    ["this", "bu"],
    ["thorough", "to'liq"],
    ["thoroughly", "to'liq"],
    ["though", "Garchi"],
    ["thought", "fikr"],
    ["thread", "ip"],
    ["threat", "tahdid"],
    ["threaten", "tahdid qilish"],
    ["threatening", "tahdid"],
    ["throat", "tomoq"],
    ["through", "orqali"],
    ["throughout", "butun davomida"],
    ["throw", "otish"],
    ["thumb", "bosh barmog'i"],
    ["thus", "shunday qilib"],
    ["ticket", "chipta"],
    ["tie", "galstuk"],
    ["tight", "qattiq"],
    ["tightly", "qattiq"],
    ["till", "qadar"],
    ["time", "vaqt"],
    ["timetable", "jadval"],
    ["tin", "qalay"],
    ["tiny", "kichik"],
    ["tip", "maslahat"],
    ["tire", "shinalar"],
    ["tired", "charchagan"],
    ["tiring", "charchagan"],
    ["title", "sarlavha"],
    ["to", "to"],
    ["today", "Bugun"],
    ["toe", "oyoq barmog'i"],
    ["together", "birga"],
    ["toilet", "hojatxona"],
    ["tomato", "pomidor"],
    ["tomorrow", "ertaga"],
    ["ton", "tonna"],
    ["tone", "ohang"],
    ["tongue", "til"],
    ["tonight", "Bugun kechqurun"],
    ["too", "ham"],
    ["tool", "asbob"],
    ["tooth", "tish"],
    ["top", "yuqori"],
    ["topic", "mavzu"],
    ["total", "jami"],
    ["totally", "butunlay"],
    ["touch", "teginish"],
    ["tough", "qattiq"],
    ["tour", "sayohat"],
    ["tourist", "sayyoh"],
    ["toward", "tomon"],
    ["towel", "sochiq"],
    ["tower", "minora"],
    ["town", "shahar"],
    ["toy", "o'yinchoq"],
    ["trace", "iz"],
    ["track", "iz"],
    ["trade", "savdo"],
    ["tradition", "an'ana"],
    ["traditional", "an'anaviy"],
    ["traffic", "trafik"],
    ["train", "poyezd"],
    ["training", "trening"],
    ["transfer", "o'tkazish"],
    ["transform", "o'zgartirish"],
    ["transition", "o'tish"],
    ["translate", "tarjima"],
    ["translation", "tarjima"],
    ["transparent", "shaffof"],
    ["transport", "transport"],
    ["transportation", "transport"],
    ["trap", "tuzoq"],
    ["trash", "axlat"],
    ["travel", "sayohat"],
    ["traveler", "sayohatchi"],
    ["treat", "davolash"],
    ["treatment", "davolash"],
    ["tree", "daraxt"],
    ["trend", "trend"],
    ["trial", "sinov"],
    ["triangle", "uchburchak"],
    ["trick", "hiyla"],
    ["trip", "sayohat"],
    ["troop", "qo'shin"],
    ["tropical", "tropik"],
    ["trouble", "muammo"],
    ["truck", "yuk mashinasi"],
    ["true", "to'g'ri"],
    ["truly", "haqiqatan"],
    ["trust", "ishonch"],
    ["truth", "haqiqat"],
    ["try", "sinab ko'ring"],
    ["try out", "tatib ko'rish"],
    ["tube", "naycha"],
    ["tune", "ohang"],
    ["tunnel", "tunnel"],
    ["turn", "burilish"],
    ["turn around", "o'girilmoq; ishni bajarmoq"],
    ["turn back", "orqaga qaytish"],
    ["twice", "ikki marta"],
    ["twin", "egizak"],
    ["twist", "burilish"],
    ["twisted", "burilgan"],
    ["type", "turi"],
    ["typical", "odatiy"],
    ["typically", "odatda"],
    ["ugly", "xunuk"],
    ["ultimate", "yakuniy"],
    ["ultimately", "oxir-oqibat"],
    ["umbrella", "soyabon"],
    ["unable", "qodir emas"],
    ["unacceptable", "qabul qilib bo'lmaydigan"],
    ["uncertain", "noaniq"],
    ["uncle", "amaki"],
    ["uncomfortable", "noqulay"],
    ["unconscious", "ongsiz"],
    ["uncontrolled", "nazoratsiz"],
    ["under", "ostida"],
    ["underground", "er osti"],
    ["underneath", "ostida"],
    ["understand", "tushunish"],
    ["understanding", "tushunish"],
    ["underwater", "suv osti"],
    ["underwear", "ichki kiyim"],
    ["undo", "bekor qilish"],
    ["unemployed", "ishsiz"],
    ["unemployment", "ishsizlik"],
    ["unexpected", "kutilmagan"],
    ["unfair", "adolatsiz"],
    ["unfortunate", "baxtsiz"],
    ["unfortunately", "afsuski"],
    ["unfriendly", "do'stona"],
    ["unhappy", "baxtsiz"],
    ["uniform", "uniforma"],
    ["unimportant", "muhim emas"],
    ["union", "birlashma"],
    ["unique", "noyob"],
    ["unit", "birlik"],
    ["unite", "birlashish"],
    ["united", "birlashgan"],
    ["universal", "universal"],
    ["universe", "koinot"],
    ["university", "universitet"],
    ["unkind", "shafqatsiz"],
    ["unknown", "noma'lum"],
    ["unless", "agar"],
    ["unlike", "o'xshamagan"],
    ["unlikely", "ehtimol emas"],
    ["unload", "tushirish"],
    ["unlucky", "omadsiz"],
    ["unnecessary", "keraksiz"],
    ["unpleasant", "yoqimsiz"],
    ["unreasonable", "asossiz"],
    ["unsteady", "beqaror"],
    ["unsuccessful", "muvaffaqiyatsiz"],
    ["until", "qa qadar"],
    ["unusual", "g'ayrioddiy"],
    ["unusually", "g'ayrioddiy"],
    ["unwilling", "irodasiz"],
    ["up", "yuqoriga"],
    ["upon", "ustiga"],
    ["upper", "yuqori"],
    ["upset", "xafa"],
    ["upside down", "ostin-ustun"],
    ["upstairs", "yuqorida"],
    ["upward", "yuqoriga"],
    ["urban", "shahar"],
    ["urge", "rag'batlantirish"],
    ["urgent", "shoshilinch"],
    ["us", "Biz"],
    ["use", "foydalanish"],
    ["used 1", "ishlatilgan 1"],
    ["used 2", "ishlatilgan 2"],
    ["used to", "ga o'rganib qolmoq, ... ga odatlanib qolmoq"],
    ["useful", "foydali"],
    ["useless", "foydasiz"],
    ["user", "foydalanuvchi"],
    ["usual", "odatiy"],
    ["usually", "odatda"],
    ["vacation", "dam olish"],
    ["valid", "yaroqli"],
    ["valley", "vodiy"],
    ["valuable", "qimmatli"],
    ["value", "qiymat"],
    ["van", "van"],
    ["variation", "variatsiya"],
    ["varied", "turli"],
    ["variety", "xilma-xillik"],
    ["various", "turli"],
    ["vary", "turli"],
    ["vast", "keng"],
    ["vegetable", "sabzavot"],
    ["vehicle", "transport vositasi"],
    ["venture", "zarba"],
    ["version", "versiya"],
    ["vertical", "vertikal"],
    ["very", "juda"],
    ["via", "orqali"],
    ["victim", "jabrlanuvchi"],
    ["victory", "g'alaba"],
    ["video", "video"],
    ["view", "ko'rinish"],
    ["violence", "zo'ravonlik"],
    ["violent", "zo'ravon"],
    ["violently", "zo'ravonlik bilan"],
    ["virtually", "deyarli"],
    ["virus", "virus"],
    ["visible", "ko'rinadigan"],
    ["vision", "ko'rish"],
    ["visit", "tashrif"],
    ["visitor", "Mehmon"],
    ["vital", "hayotiy"],
    ["vocabulary", "lug'at"],
    ["voice", "ovoz"],
    ["volume", "hajm"],
    ["vote", "ovoz berish"],
    ["wage", "ish haqi"],
    ["waist", "bel"],
    ["wait", "Kutmoq"],
    ["waiter", "Ofisiant"],
    ["wake", "uyg'onish"],
    ["walk", "yurish"],
    ["walking", "yurish"],
    ["wall", "devor"],
    ["wallet", "hamyon"],
    ["wander", "ayyorlik"],
    ["want", "xohlayman"],
    ["war", "urush"],
    ["warm", "issiq"],
    ["warmth", "issiqlik"],
    ["warn", "ogohlantirish"],
    ["warning", "ogohlantirish"],
    ["wash", "yuvish"],
    ["waste", "chiqindilar"],
    ["watch", "tomosha"],
    ["water", "suv"],
    ["wave", "to'lqin"],
    ["way", "yo'l"],
    ["we", "biz"],
    ["weak", "zaif"],
    ["weakness", "zaiflik"],
    ["wealth", "boylik"],
    ["weapon", "qurol"],
    ["wear", "kiyish"],
    ["wear away", "keyib ketish"],
    ["wear out", "eskirgan"],
    ["weather", "ob-havo"],
    ["web", "veb"],
    ["wedding", "to'y"],
    ["week", "hafta"],
    ["weekend", "hafta oxiri"],
    ["weekly", "haftalik"],
    ["weigh", "tortishish"],
    ["weight", "og'irlik"],
    [ "weird", "g'alati"],
    ["welcome", "xush kelibsiz"],
    ["well", "yaxshi"],
    ["well-known", "taniqli"],
    ["west", "g'arbiy"],
    ["western", "g'arbiy"],
    ["wet", "ho'l"],
    ["what", "nima"],
    ["whatever", "nima bo'lsa ham"],
    ["wheel", "g'ildirak"],
    ["when", "qachon"],
    ["whenever", "qachon"],
    ["where", "qaerda"],
    ["whereas", "holbuki"],
    ["wherever", "qaerda bo'lmasin"],
    ["whether", "yoki"],
    ["which", "qaysi"],
    ["while", "hozirda"],
    ["whisper", "shivirlash"],
    ["whistle", "hushtak"],
    ["white", "oq"],
    ["who", "JSSV"],
    ["whoever", "kim"],
    ["whole", "butun"],
    ["whom", "kim"],
    ["whose", "kimning"],
    ["why", "nima uchun"],
    ["wide", "keng"],
    ["widely", "keng"],
    ["width", "kenglik"],
    ["wife", "xotin"],
    ["wild", "yovvoyi"],
    ["wildly", "vahshiy"],
    ["will", "bo'ladi"],
    ["willing", "xohlagan"],
    ["win", "g'alaba"],
    ["wind 1", "shamol 1"],
    ["wind 2", "shamol 2"],
    ["window", "deraza"],
    ["wine", "vino"],
    ["wing", "qanot"],
    ["winner", "g'olib"],
    ["winning", "g'alaba"],
    ["winter", "qish"],
    ["wire", "sim"],
    ["wise", "dono"],
    ["wish", "istak"],
    ["with", "bilan"],
    ["withdraw", "olib tashlash"],
    ["within", "ichida"],
    ["without", "siz"],
    ["witness", "guvoh"],
    ["woman", "ayol"],
    ["wonder", "ajoyib"],
    ["wonderful", "ajoyib"],
    ["wood", "yog'och"],
    ["wooden", "yog'och"],
    ["wool", "jun"],
    ["word", "so'z"],
    ["work", "ish"],
    ["worker", "ishchi"],
    ["working", "ishlash"],
    ["world", "dunyo"],
    ["worried", "xavotir"],
    ["worry", "xavotir"],
    ["worrying", "tashvish"],
    ["worse", "yomonroq"],
    ["worship", "sajda qilish"],
    ["worst", "eng yomon"],
    ["worth", "arziydi"],
    ["would", "bo'lardi"],
    ["wound 1", "yara 1"],
    ["wounded", "yarador"],
    ["wrap", "o'rash"],
    ["wrist", "bilak"],
    ["write", "yozish"],
    ["writer", "yozuvchi"],
    ["writing", "yozish"],
    ["written", "yozma"],
    ["wrong", "noto'g'ri"],
    ["wrongly", "noto'g'ri"],
    ["yard", "hovli"],
    ["yawn", "esnamoq"],
    ["yeah", "ha"],
    ["year", "yil"],
    ["yellow", "sariq"],
    ["yes", "ha"],
    ["yesterday", "kecha"],
    ["yet", "hali"],
    ["you", "siz"],
    ["young", "yosh"],
    ["your", "sizning"],
    ["yours", "sizniki"],
    ["yourself", "o'zing"],
    ["youth", "yoshlik"],
    ["zero", "nol"],
    ["zone", "zona"]   
    ]
     export { arr}